const HEX_THREAD_NAME_PATTERN = /^[a-f0-9]{4,8}$/i;
const DEFAULT_THREAD_NAME_MAX_CHARS = 38;

export function looksAutoGeneratedThreadName(name: string): boolean {
  const trimmed = name.trim();
  if (!trimmed) {
    return false;
  }
  const normalized = trimmed.toLowerCase();
  return (
    normalized === "new agent" ||
    normalized === "new thread" ||
    trimmed.startsWith("Agent ") ||
    HEX_THREAD_NAME_PATTERN.test(trimmed)
  );
}

export function isMeaningfulThreadName(name: string): boolean {
  const trimmed = name.trim();
  return trimmed.length > 0 && !looksAutoGeneratedThreadName(trimmed);
}

export function getMeaningfulThreadName(name: string): string | null {
  const trimmed = name.trim();
  return isMeaningfulThreadName(trimmed) ? trimmed : null;
}

export function truncateThreadName(name: string, maxChars = DEFAULT_THREAD_NAME_MAX_CHARS): string {
  return name.length > maxChars ? `${name.slice(0, maxChars)}…` : name;
}
