import {
  CODE_RUNTIME_RPC_METHOD_LIST,
  CODE_RUNTIME_RPC_METHODS,
  type CodeRuntimeRpcMethod,
} from "@ku0/code-runtime-host-contract";

export const CODE_RUNTIME_RPC_CANONICAL_METHOD_SET: ReadonlySet<CodeRuntimeRpcMethod> = new Set(
  CODE_RUNTIME_RPC_METHOD_LIST
);

export const WEB_RUNTIME_READ_ONLY_METHODS: ReadonlySet<CodeRuntimeRpcMethod> = new Set([
  CODE_RUNTIME_RPC_METHODS.RPC_CAPABILITIES,
  CODE_RUNTIME_RPC_METHODS.HEALTH,
  CODE_RUNTIME_RPC_METHODS.SETTINGS_SUMMARY,
  CODE_RUNTIME_RPC_METHODS.REMOTE_STATUS,
  CODE_RUNTIME_RPC_METHODS.TERMINAL_STATUS,
  CODE_RUNTIME_RPC_METHODS.MODELS_POOL,
  CODE_RUNTIME_RPC_METHODS.PROVIDERS_CATALOG,
  CODE_RUNTIME_RPC_METHODS.WORKSPACES_LIST,
  CODE_RUNTIME_RPC_METHODS.BOOTSTRAP_SNAPSHOT,
  CODE_RUNTIME_RPC_METHODS.RPC_BATCH,
  CODE_RUNTIME_RPC_METHODS.WORKSPACE_FILES_LIST,
  CODE_RUNTIME_RPC_METHODS.WORKSPACE_FILE_READ,
  CODE_RUNTIME_RPC_METHODS.GIT_CHANGES_LIST,
  CODE_RUNTIME_RPC_METHODS.GIT_DIFF_READ,
  CODE_RUNTIME_RPC_METHODS.GIT_BRANCHES_LIST,
  CODE_RUNTIME_RPC_METHODS.GIT_LOG,
  CODE_RUNTIME_RPC_METHODS.PROMPT_LIBRARY_LIST,
  CODE_RUNTIME_RPC_METHODS.THREADS_LIST,
  CODE_RUNTIME_RPC_METHODS.THREAD_RESUME,
  CODE_RUNTIME_RPC_METHODS.TERMINAL_READ,
  CODE_RUNTIME_RPC_METHODS.CLI_SESSIONS_LIST,
  CODE_RUNTIME_RPC_METHODS.OAUTH_ACCOUNTS_LIST,
  CODE_RUNTIME_RPC_METHODS.OAUTH_PRIMARY_ACCOUNT_GET,
  CODE_RUNTIME_RPC_METHODS.OAUTH_POOLS_LIST,
  CODE_RUNTIME_RPC_METHODS.OAUTH_POOL_MEMBERS_LIST,
  CODE_RUNTIME_RPC_METHODS.RUNTIME_BACKENDS_LIST,
  CODE_RUNTIME_RPC_METHODS.DISTRIBUTED_TASK_GRAPH,
  CODE_RUNTIME_RPC_METHODS.LIVE_SKILLS_LIST,
  CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_METRICS_READ,
  CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_GUARDRAIL_READ,
  CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_PREFLIGHT_V2,
  CODE_RUNTIME_RPC_METHODS.ACTION_REQUIRED_GET_V2,
  CODE_RUNTIME_RPC_METHODS.RUNTIME_POLICY_GET_V2,
  CODE_RUNTIME_RPC_METHODS.KERNEL_PROJECTION_BOOTSTRAP_V3,
  CODE_RUNTIME_RPC_METHODS.CODEX_CLOUD_TASKS_LIST_V1,
  CODE_RUNTIME_RPC_METHODS.COLLABORATION_MODES_LIST_V1,
  CODE_RUNTIME_RPC_METHODS.MCP_SERVER_STATUS_LIST_V1,
  CODE_RUNTIME_RPC_METHODS.EXTENSIONS_LIST_V1,
  CODE_RUNTIME_RPC_METHODS.EXTENSION_TOOLS_LIST_V1,
  CODE_RUNTIME_RPC_METHODS.EXTENSION_RESOURCE_READ_V1,
  CODE_RUNTIME_RPC_METHODS.EXTENSIONS_CONFIG_V1,
  CODE_RUNTIME_RPC_METHODS.SESSION_EXPORT_V1,
  CODE_RUNTIME_RPC_METHODS.SECURITY_PREFLIGHT_V1,
  CODE_RUNTIME_RPC_METHODS.RUNTIME_DIAGNOSTICS_EXPORT_V1,
]);

export const WEB_RUNTIME_SHORT_CACHE_METHODS: ReadonlySet<CodeRuntimeRpcMethod> = new Set([
  CODE_RUNTIME_RPC_METHODS.BOOTSTRAP_SNAPSHOT,
]);

export function resolveCanonicalCodeRuntimeRpcMethod(method: string): CodeRuntimeRpcMethod | null {
  if (CODE_RUNTIME_RPC_CANONICAL_METHOD_SET.has(method as CodeRuntimeRpcMethod)) {
    return method as CodeRuntimeRpcMethod;
  }
  return null;
}
