import { CODE_RUNTIME_RPC_METHODS } from "@ku0/code-runtime-host-contract";

export const RUNTIME_EXTENSION_RPC_METHODS = {
  RUNTIME_BACKENDS_LIST:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_BACKENDS_LIST ?? "code_runtime_backends_list",
  RUNTIME_BACKEND_UPSERT:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_BACKEND_UPSERT ?? "code_runtime_backend_upsert",
  RUNTIME_BACKEND_REMOVE:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_BACKEND_REMOVE ?? "code_runtime_backend_remove",
  RUNTIME_BACKEND_SET_STATE:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_BACKEND_SET_STATE ?? "code_runtime_backend_set_state",
  ACP_INTEGRATIONS_LIST:
    CODE_RUNTIME_RPC_METHODS.ACP_INTEGRATIONS_LIST ?? "code_acp_integrations_list",
  ACP_INTEGRATION_UPSERT:
    CODE_RUNTIME_RPC_METHODS.ACP_INTEGRATION_UPSERT ?? "code_acp_integration_upsert",
  ACP_INTEGRATION_REMOVE:
    CODE_RUNTIME_RPC_METHODS.ACP_INTEGRATION_REMOVE ?? "code_acp_integration_remove",
  ACP_INTEGRATION_SET_STATE:
    CODE_RUNTIME_RPC_METHODS.ACP_INTEGRATION_SET_STATE ?? "code_acp_integration_set_state",
  ACP_INTEGRATION_PROBE:
    CODE_RUNTIME_RPC_METHODS.ACP_INTEGRATION_PROBE ?? "code_acp_integration_probe",
  DISTRIBUTED_TASK_GRAPH:
    CODE_RUNTIME_RPC_METHODS.DISTRIBUTED_TASK_GRAPH ?? "code_distributed_task_graph",
  OAUTH_POOL_MEMBERS_LIST:
    CODE_RUNTIME_RPC_METHODS.OAUTH_POOL_MEMBERS_LIST ?? "code_oauth_pool_members_list",
  OAUTH_POOL_APPLY: CODE_RUNTIME_RPC_METHODS.OAUTH_POOL_APPLY ?? "code_oauth_pool_apply",
  OAUTH_CHATGPT_AUTH_TOKENS_REFRESH:
    CODE_RUNTIME_RPC_METHODS.OAUTH_CHATGPT_AUTH_TOKENS_REFRESH ??
    "code_oauth_chatgpt_auth_tokens_refresh",
  CODEX_EXEC_RUN_V1: CODE_RUNTIME_RPC_METHODS.CODEX_EXEC_RUN_V1 ?? "code_codex_exec_run_v1",
  CODEX_CLOUD_TASKS_LIST_V1:
    CODE_RUNTIME_RPC_METHODS.CODEX_CLOUD_TASKS_LIST_V1 ?? "code_codex_cloud_tasks_list_v1",
  CODEX_CONFIG_PATH_GET_V1:
    CODE_RUNTIME_RPC_METHODS.CODEX_CONFIG_PATH_GET_V1 ?? "code_codex_config_path_get_v1",
  CODEX_DOCTOR_V1: CODE_RUNTIME_RPC_METHODS.CODEX_DOCTOR_V1 ?? "code_codex_doctor_v1",
  CODEX_UPDATE_V1: CODE_RUNTIME_RPC_METHODS.CODEX_UPDATE_V1 ?? "code_codex_update_v1",
  COLLABORATION_MODES_LIST_V1:
    CODE_RUNTIME_RPC_METHODS.COLLABORATION_MODES_LIST_V1 ?? "code_collaboration_modes_list_v1",
  MCP_SERVER_STATUS_LIST_V1:
    CODE_RUNTIME_RPC_METHODS.MCP_SERVER_STATUS_LIST_V1 ?? "code_mcp_server_status_list_v1",
  BROWSER_DEBUG_STATUS_V1:
    CODE_RUNTIME_RPC_METHODS.BROWSER_DEBUG_STATUS_V1 ?? "code_browser_debug_status_v1",
  BROWSER_DEBUG_RUN_V1:
    CODE_RUNTIME_RPC_METHODS.BROWSER_DEBUG_RUN_V1 ?? "code_browser_debug_run_v1",
  WORKSPACE_PATCH_APPLY_V1:
    CODE_RUNTIME_RPC_METHODS.WORKSPACE_PATCH_APPLY_V1 ?? "code_workspace_patch_apply_v1",
  WORKSPACE_DIAGNOSTICS_LIST_V1:
    CODE_RUNTIME_RPC_METHODS.WORKSPACE_DIAGNOSTICS_LIST_V1 ?? "code_workspace_diagnostics_list_v1",
  EXTENSIONS_LIST_V1: CODE_RUNTIME_RPC_METHODS.EXTENSIONS_LIST_V1 ?? "code_extensions_list_v1",
  EXTENSION_INSTALL_V1:
    CODE_RUNTIME_RPC_METHODS.EXTENSION_INSTALL_V1 ?? "code_extension_install_v1",
  EXTENSION_REMOVE_V1: CODE_RUNTIME_RPC_METHODS.EXTENSION_REMOVE_V1 ?? "code_extension_remove_v1",
  EXTENSION_TOOLS_LIST_V1:
    CODE_RUNTIME_RPC_METHODS.EXTENSION_TOOLS_LIST_V1 ?? "code_extension_tools_list_v1",
  EXTENSION_RESOURCE_READ_V1:
    CODE_RUNTIME_RPC_METHODS.EXTENSION_RESOURCE_READ_V1 ?? "code_extension_resource_read_v1",
  EXTENSIONS_CONFIG_V1:
    CODE_RUNTIME_RPC_METHODS.EXTENSIONS_CONFIG_V1 ?? "code_extensions_config_v1",
  SESSION_EXPORT_V1: CODE_RUNTIME_RPC_METHODS.SESSION_EXPORT_V1 ?? "code_session_export_v1",
  SESSION_IMPORT_V1: CODE_RUNTIME_RPC_METHODS.SESSION_IMPORT_V1 ?? "code_session_import_v1",
  SESSION_DELETE_V1: CODE_RUNTIME_RPC_METHODS.SESSION_DELETE_V1 ?? "code_session_delete_v1",
  THREAD_SNAPSHOTS_GET_V1:
    CODE_RUNTIME_RPC_METHODS.THREAD_SNAPSHOTS_GET_V1 ?? "code_thread_snapshots_get_v1",
  THREAD_SNAPSHOTS_SET_V1:
    CODE_RUNTIME_RPC_METHODS.THREAD_SNAPSHOTS_SET_V1 ?? "code_thread_snapshots_set_v1",
  SECURITY_PREFLIGHT_V1:
    CODE_RUNTIME_RPC_METHODS.SECURITY_PREFLIGHT_V1 ?? "code_security_preflight_v1",
  RUNTIME_DIAGNOSTICS_EXPORT_V1:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_DIAGNOSTICS_EXPORT_V1 ?? "code_runtime_diagnostics_export_v1",
} as const;

export const THREAD_LIVE_RPC_METHODS = {
  THREAD_LIVE_SUBSCRIBE:
    CODE_RUNTIME_RPC_METHODS.THREAD_LIVE_SUBSCRIBE ?? "code_thread_live_subscribe",
  THREAD_LIVE_UNSUBSCRIBE:
    CODE_RUNTIME_RPC_METHODS.THREAD_LIVE_UNSUBSCRIBE ?? "code_thread_live_unsubscribe",
} as const;

export const OPTIONAL_RUNTIME_RPC_METHODS = {
  WORKSPACE_PICK_DIRECTORY:
    CODE_RUNTIME_RPC_METHODS.WORKSPACE_PICK_DIRECTORY ?? "code_workspace_pick_directory",
  SUB_AGENT_SPAWN: CODE_RUNTIME_RPC_METHODS.SUB_AGENT_SPAWN ?? "code_sub_agent_spawn",
  SUB_AGENT_SEND: CODE_RUNTIME_RPC_METHODS.SUB_AGENT_SEND ?? "code_sub_agent_send",
  SUB_AGENT_WAIT: CODE_RUNTIME_RPC_METHODS.SUB_AGENT_WAIT ?? "code_sub_agent_wait",
  SUB_AGENT_STATUS: CODE_RUNTIME_RPC_METHODS.SUB_AGENT_STATUS ?? "code_sub_agent_status",
  SUB_AGENT_INTERRUPT: CODE_RUNTIME_RPC_METHODS.SUB_AGENT_INTERRUPT ?? "code_sub_agent_interrupt",
  SUB_AGENT_CLOSE: CODE_RUNTIME_RPC_METHODS.SUB_AGENT_CLOSE ?? "code_sub_agent_close",
  BOOTSTRAP_SNAPSHOT: CODE_RUNTIME_RPC_METHODS.BOOTSTRAP_SNAPSHOT ?? "code_bootstrap_snapshot",
} as const;

export const RUNTIME_TOOL_METRICS_RPC_METHODS = {
  RUNTIME_TOOL_METRICS_RECORD:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_METRICS_RECORD ?? "code_runtime_tool_metrics_record",
  RUNTIME_TOOL_METRICS_READ:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_METRICS_READ ?? "code_runtime_tool_metrics_read",
  RUNTIME_TOOL_METRICS_RESET:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_METRICS_RESET ?? "code_runtime_tool_metrics_reset",
  RUNTIME_TOOL_GUARDRAIL_EVALUATE:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_GUARDRAIL_EVALUATE ??
    "code_runtime_tool_guardrail_evaluate",
  RUNTIME_TOOL_GUARDRAIL_RECORD_OUTCOME:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_GUARDRAIL_RECORD_OUTCOME ??
    "code_runtime_tool_guardrail_record_outcome",
  RUNTIME_TOOL_GUARDRAIL_READ:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_GUARDRAIL_READ ?? "code_runtime_tool_guardrail_read",
} as const;

export const RUNTIME_AUTONOMY_V2_RPC_METHODS = {
  RUNTIME_TOOL_PREFLIGHT_V2:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_PREFLIGHT_V2 ?? "code_runtime_tool_preflight_v2",
  ACTION_REQUIRED_SUBMIT_V2:
    CODE_RUNTIME_RPC_METHODS.ACTION_REQUIRED_SUBMIT_V2 ?? "code_action_required_submit_v2",
  ACTION_REQUIRED_GET_V2:
    CODE_RUNTIME_RPC_METHODS.ACTION_REQUIRED_GET_V2 ?? "code_action_required_get_v2",
  RUNTIME_TOOL_OUTCOME_RECORD_V2:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_TOOL_OUTCOME_RECORD_V2 ??
    "code_runtime_tool_outcome_record_v2",
  RUNTIME_POLICY_GET_V2:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_POLICY_GET_V2 ?? "code_runtime_policy_get_v2",
  RUNTIME_POLICY_SET_V2:
    CODE_RUNTIME_RPC_METHODS.RUNTIME_POLICY_SET_V2 ?? "code_runtime_policy_set_v2",
} as const;

export const RUNTIME_KERNEL_V2_RPC_METHODS = {
  KERNEL_CAPABILITIES_LIST_V2:
    CODE_RUNTIME_RPC_METHODS.KERNEL_CAPABILITIES_LIST_V2 ?? "code_kernel_capabilities_list_v2",
  KERNEL_SESSIONS_LIST_V2:
    CODE_RUNTIME_RPC_METHODS.KERNEL_SESSIONS_LIST_V2 ?? "code_kernel_sessions_list_v2",
  KERNEL_JOBS_LIST_V2: CODE_RUNTIME_RPC_METHODS.KERNEL_JOBS_LIST_V2 ?? "code_kernel_jobs_list_v2",
  KERNEL_CONTEXT_SNAPSHOT_V2:
    CODE_RUNTIME_RPC_METHODS.KERNEL_CONTEXT_SNAPSHOT_V2 ?? "code_kernel_context_snapshot_v2",
  KERNEL_EXTENSIONS_LIST_V2:
    CODE_RUNTIME_RPC_METHODS.KERNEL_EXTENSIONS_LIST_V2 ?? "code_kernel_extensions_list_v2",
  KERNEL_POLICIES_EVALUATE_V2:
    CODE_RUNTIME_RPC_METHODS.KERNEL_POLICIES_EVALUATE_V2 ?? "code_kernel_policies_evaluate_v2",
  KERNEL_PROJECTION_BOOTSTRAP_V3:
    CODE_RUNTIME_RPC_METHODS.KERNEL_PROJECTION_BOOTSTRAP_V3 ??
    "code_kernel_projection_bootstrap_v3",
} as const;
