export const RUNTIME_MESSAGE_CODES = {
  webmcp: {
    intent: {
      updateSuccess: "webmcp.intent.update.success",
      overviewRetrieved: "webmcp.intent.overview.retrieved",
    },
    governance: {
      policyUpdated: "webmcp.governance.policy.updated",
      cycleExecuted: "webmcp.governance.cycle.executed",
      statusRetrieved: "webmcp.governance.status.retrieved",
      auditLogRetrieved: "webmcp.governance.audit_log.retrieved",
    },
    task: {
      listRetrieved: "webmcp.task.list.retrieved",
      ownerLoadRetrieved: "webmcp.task.owner_load.retrieved",
      upsertSuccess: "webmcp.task.upsert.success",
      moveSuccess: "webmcp.task.move.success",
      pauseSuccess: "webmcp.task.pause.success",
      resumeSuccess: "webmcp.task.resume.success",
      terminateSuccess: "webmcp.task.terminate.success",
      rebalanceSuccess: "webmcp.task.rebalance.success",
      assignSuccess: "webmcp.task.assign.success",
      removeSuccess: "webmcp.task.remove.success",
      clearCompletedSuccess: "webmcp.task.clear_completed.success",
    },
  },
  runtime: {
    task: {
      listRetrieved: "runtime.task.list.retrieved",
      statusRetrieved: "runtime.task.status.retrieved",
      startSubmitted: "runtime.task.start.submitted",
      interruptSubmitted: "runtime.task.interrupt.submitted",
      terminateSubmitted: "runtime.task.terminate.submitted",
    },
    subAgent: {
      sessionExecuted: "runtime.sub_agent.session.execute.completed",
      sessionSpawned: "runtime.sub_agent.session.spawn.submitted",
      instructionDispatched: "runtime.sub_agent.instruction.send.submitted",
      sessionWaitCompleted: "runtime.sub_agent.session.wait.completed",
      sessionStatusRetrieved: "runtime.sub_agent.session.status.retrieved",
      sessionInterruptSubmitted: "runtime.sub_agent.session.interrupt.submitted",
      sessionCloseSubmitted: "runtime.sub_agent.session.close.submitted",
    },
    liveSkill: {
      listRetrieved: "runtime.live_skill.list.retrieved",
      runCompleted: "runtime.live_skill.run.completed",
    },
    computerObserve: {
      runCompleted: "runtime.computer_observe.run.completed",
    },
    toolExecution: {
      metricsRetrieved: "runtime.tool_execution.metrics.retrieved",
      guardrailStateRetrieved: "runtime.tool_execution.guardrail_state.retrieved",
    },
    file: {
      searchCompleted: "runtime.file.search.completed",
      treeListed: "runtime.file.tree.listed",
      readCompleted: "runtime.file.read.completed",
      writeCompleted: "runtime.file.write.completed",
      editCompleted: "runtime.file.edit.completed",
    },
    command: {
      workspaceCommandCompleted: "runtime.command.workspace.execute.completed",
      networkAnalysisCompleted: "runtime.command.network_analysis.completed",
      gitStatusRetrieved: "runtime.command.git.status.retrieved",
      gitDiffsRetrieved: "runtime.command.git.diffs.retrieved",
      gitBranchesRetrieved: "runtime.command.git.branches.retrieved",
      gitStageFileCompleted: "runtime.command.git.stage_file.completed",
      gitStageAllCompleted: "runtime.command.git.stage_all.completed",
      gitUnstageFileCompleted: "runtime.command.git.unstage_file.completed",
      gitRevertFileCompleted: "runtime.command.git.revert_file.completed",
      gitCommitCompleted: "runtime.command.git.commit.completed",
      gitCreateBranchCompleted: "runtime.command.git.create_branch.completed",
      gitCheckoutBranchCompleted: "runtime.command.git.checkout_branch.completed",
    },
    validation: {
      backendsListed: "runtime.validation.backends.listed",
      distributedTaskGraphRetrieved: "runtime.validation.distributed_task_graph.retrieved",
      capabilitiesSummaryRetrieved: "runtime.validation.capabilities_summary.retrieved",
      healthRetrieved: "runtime.validation.health.retrieved",
      terminalStatusRetrieved: "runtime.validation.terminal_status.retrieved",
      inputRequired: "runtime.validation.input.required",
      inputInvalid: "runtime.validation.input.invalid",
      pathOutsideWorkspace: "runtime.validation.path.outside_workspace",
      payloadTooLarge: "runtime.validation.payload.too_large",
      payloadTooLargeStrict: "runtime.validation.payload_too_large",
      commandRestricted: "runtime.validation.command.restricted",
      methodUnavailable: "runtime.validation.method.unavailable",
      metricsUnavailable: "runtime.validation.metrics.unavailable",
      metricsUnhealthy: "runtime.validation.metrics_unhealthy",
      circuitOpen: "runtime.validation.circuit_open",
      rateLimited: "runtime.validation.rate_limited",
      resourceNotFound: "runtime.validation.resource.not_found",
      requestBlocked: "runtime.validation.request.blocked",
      approvalRejected: "runtime.validation.approval.rejected",
      unknownError: "runtime.validation.error.unknown",
      messageUnmapped: "runtime.validation.message.unmapped",
    },
    terminal: {
      sessionOpened: "runtime.terminal.session.opened",
      sessionRead: "runtime.terminal.session.read",
      sessionWritten: "runtime.terminal.session.written",
      sessionInterrupted: "runtime.terminal.session.interrupted",
      sessionResized: "runtime.terminal.session.resized",
      sessionClosed: "runtime.terminal.session.closed",
    },
    batch: {
      interruptActiveNoop: "runtime.batch.interrupt_active.noop",
      interruptActiveSubmitted: "runtime.batch.interrupt_active.submitted",
    },
    approval: {
      decisionSubmitted: "runtime.approval.decision.submitted",
      queueRetrieved: "runtime.approval.queue.retrieved",
      poolVersionMismatch: "runtime.approval.pool.version_mismatch",
    },
    actionRequired: {
      listRetrieved: "runtime.action_required.list.retrieved",
      itemRetrieved: "runtime.action_required.item.retrieved",
      itemResolved: "runtime.action_required.item.resolved",
    },
    maintenance: {
      codexDoctorCompleted: "runtime.maintenance.codex_doctor.completed",
      codexUpdateCompleted: "runtime.maintenance.codex_update.completed",
    },
    prompt: {
      listRetrieved: "runtime.prompt.list.retrieved",
      created: "runtime.prompt.created",
      updated: "runtime.prompt.updated",
      deleted: "runtime.prompt.deleted",
      moved: "runtime.prompt.moved",
    },
    oauth: {
      accountsRetrieved: "runtime.oauth.accounts.retrieved",
      accountInfoRetrieved: "runtime.oauth.account_info.retrieved",
      accountRateLimitsRetrieved: "runtime.oauth.account_rate_limits.retrieved",
      accountUpserted: "runtime.oauth.account.upserted",
      accountRemoved: "runtime.oauth.account.removed",
      poolsRetrieved: "runtime.oauth.pools.retrieved",
      poolMembersRetrieved: "runtime.oauth.pool_members.retrieved",
      poolApplied: "runtime.oauth.pool.applied",
      poolRemoved: "runtime.oauth.pool.removed",
      poolSelectionRetrieved: "runtime.oauth.pool_selection.retrieved",
    },
    extension: {
      installCompleted: "runtime.extension.install.completed",
      removeCompleted: "runtime.extension.remove.completed",
    },
  },
} as const;

const RESPONSE_MESSAGE_CODE_BY_MESSAGE: Record<string, string> = {
  "Project overview retrieved.": RUNTIME_MESSAGE_CODES.webmcp.intent.overviewRetrieved,
  "Project tasks retrieved.": RUNTIME_MESSAGE_CODES.webmcp.task.listRetrieved,
  "Governance status retrieved.": RUNTIME_MESSAGE_CODES.webmcp.governance.statusRetrieved,
  "Owner load summary retrieved.": RUNTIME_MESSAGE_CODES.webmcp.task.ownerLoadRetrieved,
  "Agent audit log retrieved.": RUNTIME_MESSAGE_CODES.webmcp.governance.auditLogRetrieved,
  "Intent updated.": RUNTIME_MESSAGE_CODES.webmcp.intent.updateSuccess,
  "Governance policy updated.": RUNTIME_MESSAGE_CODES.webmcp.governance.policyUpdated,
  "Governance cycle executed.": RUNTIME_MESSAGE_CODES.webmcp.governance.cycleExecuted,
  "Task upserted.": RUNTIME_MESSAGE_CODES.webmcp.task.upsertSuccess,
  "Task moved.": RUNTIME_MESSAGE_CODES.webmcp.task.moveSuccess,
  "Task paused.": RUNTIME_MESSAGE_CODES.webmcp.task.pauseSuccess,
  "Task resumed.": RUNTIME_MESSAGE_CODES.webmcp.task.resumeSuccess,
  "Task terminated.": RUNTIME_MESSAGE_CODES.webmcp.task.terminateSuccess,
  "Task ownership rebalanced.": RUNTIME_MESSAGE_CODES.webmcp.task.rebalanceSuccess,
  "Task owner updated.": RUNTIME_MESSAGE_CODES.webmcp.task.assignSuccess,
  "Task removed.": RUNTIME_MESSAGE_CODES.webmcp.task.removeSuccess,
  "Completed tasks cleared.": RUNTIME_MESSAGE_CODES.webmcp.task.clearCompletedSuccess,
  "Runtime tasks retrieved.": RUNTIME_MESSAGE_CODES.runtime.task.listRetrieved,
  "Runtime task status retrieved.": RUNTIME_MESSAGE_CODES.runtime.task.statusRetrieved,
  "Runtime live skills retrieved.": RUNTIME_MESSAGE_CODES.runtime.liveSkill.listRetrieved,
  "Runtime tool execution metrics retrieved.":
    RUNTIME_MESSAGE_CODES.runtime.toolExecution.metricsRetrieved,
  "Runtime tool guardrail state retrieved.":
    RUNTIME_MESSAGE_CODES.runtime.toolExecution.guardrailStateRetrieved,
  "Runtime backends listed.": RUNTIME_MESSAGE_CODES.runtime.validation.backendsListed,
  "Runtime distributed task graph retrieved.":
    RUNTIME_MESSAGE_CODES.runtime.validation.distributedTaskGraphRetrieved,
  "Runtime capabilities summary retrieved.":
    RUNTIME_MESSAGE_CODES.runtime.validation.capabilitiesSummaryRetrieved,
  "Runtime health retrieved.": RUNTIME_MESSAGE_CODES.runtime.validation.healthRetrieved,
  "Runtime terminal status retrieved.":
    RUNTIME_MESSAGE_CODES.runtime.validation.terminalStatusRetrieved,
  "Runtime terminal session opened.": RUNTIME_MESSAGE_CODES.runtime.terminal.sessionOpened,
  "Runtime terminal session read.": RUNTIME_MESSAGE_CODES.runtime.terminal.sessionRead,
  "Runtime terminal session written.": RUNTIME_MESSAGE_CODES.runtime.terminal.sessionWritten,
  "Runtime terminal session interrupted.":
    RUNTIME_MESSAGE_CODES.runtime.terminal.sessionInterrupted,
  "Runtime terminal session resized.": RUNTIME_MESSAGE_CODES.runtime.terminal.sessionResized,
  "Runtime terminal session closed.": RUNTIME_MESSAGE_CODES.runtime.terminal.sessionClosed,
  "Workspace file search completed.": RUNTIME_MESSAGE_CODES.runtime.file.searchCompleted,
  "Workspace tree listed.": RUNTIME_MESSAGE_CODES.runtime.file.treeListed,
  "Workspace file read completed.": RUNTIME_MESSAGE_CODES.runtime.file.readCompleted,
  "Workspace file write completed.": RUNTIME_MESSAGE_CODES.runtime.file.writeCompleted,
  "Workspace file edit completed.": RUNTIME_MESSAGE_CODES.runtime.file.editCompleted,
  "Workspace command executed.": RUNTIME_MESSAGE_CODES.runtime.command.workspaceCommandCompleted,
  "Network analysis completed.": RUNTIME_MESSAGE_CODES.runtime.command.networkAnalysisCompleted,
  "Runtime live skill executed.": RUNTIME_MESSAGE_CODES.runtime.liveSkill.runCompleted,
  "Runtime computer observe completed.": RUNTIME_MESSAGE_CODES.runtime.computerObserve.runCompleted,
  "Runtime sub-agent session executed.": RUNTIME_MESSAGE_CODES.runtime.subAgent.sessionExecuted,
  "Runtime agent task started.": RUNTIME_MESSAGE_CODES.runtime.task.startSubmitted,
  "Runtime sub-agent session spawned.": RUNTIME_MESSAGE_CODES.runtime.subAgent.sessionSpawned,
  "Runtime sub-agent instruction dispatched.":
    RUNTIME_MESSAGE_CODES.runtime.subAgent.instructionDispatched,
  "Runtime sub-agent session wait completed.":
    RUNTIME_MESSAGE_CODES.runtime.subAgent.sessionWaitCompleted,
  "Runtime sub-agent session status retrieved.":
    RUNTIME_MESSAGE_CODES.runtime.subAgent.sessionStatusRetrieved,
  "Runtime sub-agent session interruption submitted.":
    RUNTIME_MESSAGE_CODES.runtime.subAgent.sessionInterruptSubmitted,
  "Runtime sub-agent session close submitted.":
    RUNTIME_MESSAGE_CODES.runtime.subAgent.sessionCloseSubmitted,
  "Runtime task interruption submitted.": RUNTIME_MESSAGE_CODES.runtime.task.interruptSubmitted,
  "Runtime task termination submitted.": RUNTIME_MESSAGE_CODES.runtime.task.terminateSubmitted,
  "Runtime approval decision submitted.": RUNTIME_MESSAGE_CODES.runtime.approval.decisionSubmitted,
  "Runtime approval queue retrieved.": RUNTIME_MESSAGE_CODES.runtime.approval.queueRetrieved,
  "Runtime action-required items retrieved.":
    RUNTIME_MESSAGE_CODES.runtime.actionRequired.listRetrieved,
  "Runtime action-required item retrieved.":
    RUNTIME_MESSAGE_CODES.runtime.actionRequired.itemRetrieved,
  "Runtime action-required item resolved.":
    RUNTIME_MESSAGE_CODES.runtime.actionRequired.itemResolved,
  "Runtime codex doctor completed.": RUNTIME_MESSAGE_CODES.runtime.maintenance.codexDoctorCompleted,
  "Runtime codex update completed.": RUNTIME_MESSAGE_CODES.runtime.maintenance.codexUpdateCompleted,
  "Runtime prompts retrieved.": RUNTIME_MESSAGE_CODES.runtime.prompt.listRetrieved,
  "Runtime prompt created.": RUNTIME_MESSAGE_CODES.runtime.prompt.created,
  "Runtime prompt updated.": RUNTIME_MESSAGE_CODES.runtime.prompt.updated,
  "Runtime prompt deleted.": RUNTIME_MESSAGE_CODES.runtime.prompt.deleted,
  "Runtime prompt moved.": RUNTIME_MESSAGE_CODES.runtime.prompt.moved,
  "Runtime OAuth accounts retrieved.": RUNTIME_MESSAGE_CODES.runtime.oauth.accountsRetrieved,
  "Runtime account info retrieved.": RUNTIME_MESSAGE_CODES.runtime.oauth.accountInfoRetrieved,
  "Runtime account rate limits retrieved.":
    RUNTIME_MESSAGE_CODES.runtime.oauth.accountRateLimitsRetrieved,
  "Runtime OAuth account upserted.": RUNTIME_MESSAGE_CODES.runtime.oauth.accountUpserted,
  "Runtime OAuth account removed.": RUNTIME_MESSAGE_CODES.runtime.oauth.accountRemoved,
  "Runtime OAuth pools retrieved.": RUNTIME_MESSAGE_CODES.runtime.oauth.poolsRetrieved,
  "Runtime OAuth pool members retrieved.": RUNTIME_MESSAGE_CODES.runtime.oauth.poolMembersRetrieved,
  "Runtime OAuth pool applied.": RUNTIME_MESSAGE_CODES.runtime.oauth.poolApplied,
  "Runtime OAuth pool removed.": RUNTIME_MESSAGE_CODES.runtime.oauth.poolRemoved,
  "Runtime OAuth pool account selected.":
    RUNTIME_MESSAGE_CODES.runtime.oauth.poolSelectionRetrieved,
  "Runtime extension installed.": RUNTIME_MESSAGE_CODES.runtime.extension.installCompleted,
  "Runtime extension removed.": RUNTIME_MESSAGE_CODES.runtime.extension.removeCompleted,
  "No active runtime tasks to interrupt.": RUNTIME_MESSAGE_CODES.runtime.batch.interruptActiveNoop,
  "Active runtime tasks interrupted.": RUNTIME_MESSAGE_CODES.runtime.batch.interruptActiveSubmitted,
  "Runtime git status retrieved.": RUNTIME_MESSAGE_CODES.runtime.command.gitStatusRetrieved,
  "Runtime git diffs retrieved.": RUNTIME_MESSAGE_CODES.runtime.command.gitDiffsRetrieved,
  "Runtime git branches retrieved.": RUNTIME_MESSAGE_CODES.runtime.command.gitBranchesRetrieved,
  "Runtime git file staged.": RUNTIME_MESSAGE_CODES.runtime.command.gitStageFileCompleted,
  "Runtime git changes staged.": RUNTIME_MESSAGE_CODES.runtime.command.gitStageAllCompleted,
  "Runtime git file unstaged.": RUNTIME_MESSAGE_CODES.runtime.command.gitUnstageFileCompleted,
  "Runtime git file reverted.": RUNTIME_MESSAGE_CODES.runtime.command.gitRevertFileCompleted,
  "Runtime git commit created.": RUNTIME_MESSAGE_CODES.runtime.command.gitCommitCompleted,
  "Runtime git branch created.": RUNTIME_MESSAGE_CODES.runtime.command.gitCreateBranchCompleted,
  "Runtime git branch checked out.":
    RUNTIME_MESSAGE_CODES.runtime.command.gitCheckoutBranchCompleted,
};

export function resolveRuntimeMessageCode(message: string): string {
  return (
    RESPONSE_MESSAGE_CODE_BY_MESSAGE[message] ??
    RUNTIME_MESSAGE_CODES.runtime.validation.messageUnmapped
  );
}
