import { globalStyle } from "@vanilla-extract/css";
import { dsCompatSemanticVars } from "./dsCompatSemanticVars";
import { layers } from "../system/layers.css";
const semanticThemeVars = dsCompatSemanticVars;

globalStyle(":root", {
  "@layer": {
    [layers.tokens]: {
      /*
       * Temporary compatibility shim.
       * Do not add new runtime tokens here.
       * New compat families must be registered in scripts/lib/style-compat-config.mjs.
       * Shared token ownership belongs to @ku0/design-system.
       */
      /*
       * Legacy compatibility bridge:
       * DS-owned runtime primitives feed the legacy ds-* and color-* surface
       * so app shells can migrate incrementally without keeping the old
       * app-local theme runtime alive.
       */

      "--ds-color-white": semanticThemeVars.color.text.inverse,
      "--ds-color-black": semanticThemeVars.color.bg.canvas,

      "--ds-space-px": semanticThemeVars.space.px,
      "--ds-space-1": semanticThemeVars.space.xs,
      "--ds-space-2": semanticThemeVars.space.sm,
      "--ds-space-3": semanticThemeVars.space.md,
      "--ds-space-4": semanticThemeVars.space.lg,
      "--ds-space-5": semanticThemeVars.space.xl,
      "--ds-space-6": semanticThemeVars.space.x2,
      "--ds-space-8": semanticThemeVars.space.x3,
      "--ds-space-10": semanticThemeVars.space.x4,
      "--ds-space-12": semanticThemeVars.space.x5,
      "--ds-space-16": semanticThemeVars.space.x6,

      "--font-sans": semanticThemeVars.typography.font.ui,
      "--font-mono": semanticThemeVars.typography.font.mono,
      "--ui-font-family": semanticThemeVars.typography.font.ui,
      "--font-size-tiny": semanticThemeVars.typography.size.xs,
      "--font-size-micro": semanticThemeVars.typography.size.xs,
      "--font-size-fine": semanticThemeVars.typography.size.sm,
      "--font-size-meta": semanticThemeVars.typography.size.md,
      "--font-size-chrome": semanticThemeVars.typography.size.md,
      "--font-size-label": semanticThemeVars.typography.size.lg,
      "--font-size-content": semanticThemeVars.typography.size.xl,
      "--font-size-title": semanticThemeVars.typography.size.xl,
      "--font-size-title-lg": semanticThemeVars.typography.size.x2,
      "--font-size-display-sm": semanticThemeVars.typography.size.x3,
      "--font-size-display": semanticThemeVars.typography.size.x4,
      "--line-height-label": semanticThemeVars.typography.lineHeight.sm,
      "--line-height-title": semanticThemeVars.typography.lineHeight.sm,
      "--line-height-title-lg": semanticThemeVars.typography.lineHeight.tight,

      "--radius": semanticThemeVars.radius.sm,
      "--radius-sm": semanticThemeVars.radius.xs,
      "--radius-md": semanticThemeVars.radius.sm,
      "--radius-lg": semanticThemeVars.radius.md,
      "--radius-xl": semanticThemeVars.radius.lg,
      "--radius-2xl": semanticThemeVars.radius.xl,
      "--radius-3xl": semanticThemeVars.radius.x2,
      "--radius-full": semanticThemeVars.radius.pill,
      "--ds-radius-xs": semanticThemeVars.radius.xs,
      "--ds-radius-sm": semanticThemeVars.radius.sm,
      "--ds-radius-md": semanticThemeVars.radius.md,
      "--ds-radius-lg": semanticThemeVars.radius.lg,
      "--ds-radius-xl": semanticThemeVars.radius.xl,
      "--ds-radius-2xl": semanticThemeVars.radius.x2,
      "--ds-radius-3xl": semanticThemeVars.radius.x2,
      "--ds-radius-full": semanticThemeVars.radius.pill,
      "--ds-radius-button": semanticThemeVars.radius.md,
      "--ds-radius-card": semanticThemeVars.radius.xl,
      "--ds-radius-input": semanticThemeVars.radius.lg,
      "--ds-radius-pill": semanticThemeVars.radius.pill,

      "--ds-shadow-color": semanticThemeVars.color.bg.canvas,
      "--shadow-xs": semanticThemeVars.shadow.xs,
      "--shadow-sm": semanticThemeVars.shadow.sm,
      "--shadow-md": semanticThemeVars.shadow.md,
      "--shadow-lg": semanticThemeVars.shadow.lg,
      "--shadow-xl": semanticThemeVars.shadow.overlay,
      "--ds-shadow-xs": semanticThemeVars.shadow.xs,
      "--ds-shadow-sm": semanticThemeVars.shadow.sm,
      "--ds-shadow-md": semanticThemeVars.shadow.md,
      "--ds-shadow-lg": semanticThemeVars.shadow.lg,
      "--ds-shadow-xl": semanticThemeVars.shadow.overlay,
      "--ds-shadow-2xl": semanticThemeVars.shadow.overlay,
      "--ds-shadow-floating": semanticThemeVars.shadow.overlay,
      "--ds-elevation-1": semanticThemeVars.shadow.sm,
      "--ds-elevation-2": semanticThemeVars.shadow.md,
      "--elevation-card": semanticThemeVars.shadow.sm,
      "--elevation-panel": semanticThemeVars.shadow.md,
      "--elevation-floating": semanticThemeVars.shadow.lg,
      "--elevation-overlay": semanticThemeVars.shadow.overlay,

      "--duration-fast": semanticThemeVars.motion.duration.fast,
      "--duration-normal": semanticThemeVars.motion.duration.base,
      "--duration-slow": semanticThemeVars.motion.duration.slow,
      "--ease-smooth": semanticThemeVars.motion.easing.standard,
      "--ds-motion-instant": semanticThemeVars.motion.duration.instant,
      "--ds-motion-fast": semanticThemeVars.motion.duration.fast,
      "--ds-motion-base": semanticThemeVars.motion.duration.base,
      "--ds-motion-slow": semanticThemeVars.motion.duration.slow,
      "--ds-motion-slower": semanticThemeVars.motion.duration.slow,
      "--ds-motion-ease-linear": "linear",
      "--ds-motion-ease-standard": semanticThemeVars.motion.easing.standard,
      "--ds-motion-ease-enter": semanticThemeVars.motion.easing.enter,
      "--ds-motion-ease-exit": semanticThemeVars.motion.easing.exit,
      "--ds-motion-spin-duration": "1s",
      "--ds-motion-pulse-duration": "1.6s",
      "--ds-motion-shimmer-duration": "1.5s",

      "--z-popover": semanticThemeVars.layer.popover,
      "--z-tooltip": semanticThemeVars.layer.dropdown,
      "--z-modal": semanticThemeVars.layer.modal,
      "--z-toast": semanticThemeVars.layer.toast,
      "--control-height-md": semanticThemeVars.size.control.md,

      "--ds-focus-ring": semanticThemeVars.color.border.focus,
      "--ds-focus-ring-offset": semanticThemeVars.motion.focus.offset,
      "--ds-focus-ring-width": semanticThemeVars.motion.focus.width,
      "--focus-ring-input": "2px solid color-mix(in srgb, var(--ds-focus-ring) 72%, transparent)",
      "--focus-ring-overlay": "2px solid color-mix(in srgb, var(--ds-focus-ring) 66%, transparent)",
      "--focus-ring-button":
        "0 0 0 var(--ds-focus-ring-offset) color-mix(in srgb, var(--ds-surface-card-base) 86%, transparent), 0 0 0 calc(var(--ds-focus-ring-offset) + var(--ds-focus-ring-width)) var(--ds-focus-ring)",

      "--ds-gradient-soft":
        "linear-gradient(180deg, color-mix(in srgb, var(--ds-surface-card-base) 96%, transparent), color-mix(in srgb, var(--ds-surface-card) 88%, transparent))",
      "--ds-gradient-primary":
        "linear-gradient(135deg, color-mix(in srgb, var(--ds-brand-primary) 92%, white 8%), color-mix(in srgb, var(--ds-brand-secondary) 88%, white 12%))",

      "--ds-surface-canvas": semanticThemeVars.color.bg.canvas,
      "--ds-surface-app": semanticThemeVars.color.bg.app,
      "--ds-surface-sidebar": semanticThemeVars.color.bg.sidebar,
      "--ds-surface-sidebar-opaque": semanticThemeVars.color.bg.sidebar,
      "--ds-surface-topbar": semanticThemeVars.color.bg.topbar,
      "--ds-surface-right-panel": semanticThemeVars.color.bg.panel,
      "--ds-surface-panel": semanticThemeVars.color.bg.panel,
      "--ds-surface-composer": semanticThemeVars.color.bg.composer,
      "--ds-surface-messages": semanticThemeVars.color.bg.message,
      "--ds-surface-card": semanticThemeVars.color.bg.elevated,
      "--ds-surface-card-base": semanticThemeVars.color.bg.card,
      "--ds-surface-elevated": semanticThemeVars.color.bg.elevated,
      "--ds-surface-muted": semanticThemeVars.color.bg.inset,
      "--ds-surface-item": semanticThemeVars.color.bg.card,
      "--ds-surface-control": semanticThemeVars.color.control.default,
      "--ds-surface-control-hover": semanticThemeVars.color.control.hover,
      "--ds-surface-control-disabled":
        "color-mix(in srgb, var(--ds-surface-control) 42%, transparent)",
      "--ds-surface-hover": semanticThemeVars.color.bg.hover,
      "--ds-surface-active": semanticThemeVars.color.bg.pressed,
      "--ds-surface-selected": semanticThemeVars.color.bg.selected,
      "--ds-surface-approval": semanticThemeVars.color.bg.overlay,
      "--ds-surface-debug": semanticThemeVars.color.bg.overlay,
      "--ds-surface-command": semanticThemeVars.color.bg.overlay,
      "--ds-surface-diff-card": semanticThemeVars.color.bg.inset,
      "--ds-surface-bubble": semanticThemeVars.color.bg.card,
      "--ds-surface-bubble-user": semanticThemeVars.color.bg.selected,
      "--ds-surface-context-core": semanticThemeVars.color.bg.overlay,
      "--ds-surface-overlay": semanticThemeVars.color.bg.overlay,
      "--ds-surface-popover": semanticThemeVars.color.bg.elevated,
      "--ds-surface-review": semanticThemeVars.color.bg.selected,
      "--ds-surface-review-active": semanticThemeVars.color.control.selected,
      "--ds-surface-review-done":
        "color-mix(in srgb, var(--ds-status-success) 14%, var(--ds-surface-card-base))",
      "--ds-surface-shell": semanticThemeVars.color.bg.app,

      "--ds-border-subtle": semanticThemeVars.color.border.subtle,
      "--ds-border-muted": semanticThemeVars.color.border.default,
      "--ds-border-quiet": semanticThemeVars.color.border.default,
      "--ds-border-default": semanticThemeVars.color.border.default,
      "--ds-border-strong": semanticThemeVars.color.border.strong,
      "--ds-border-stronger": semanticThemeVars.color.border.strong,
      "--ds-border-accent": semanticThemeVars.color.border.accent,
      "--ds-border-accent-soft": semanticThemeVars.color.border.focus,

      "--ds-text-strong": semanticThemeVars.color.text.primary,
      "--ds-text-primary": semanticThemeVars.color.text.primary,
      "--ds-text-emphasis": semanticThemeVars.color.text.primary,
      "--ds-text-stronger": semanticThemeVars.color.text.primary,
      "--ds-text-quiet": semanticThemeVars.color.text.secondary,
      "--ds-text-muted": semanticThemeVars.color.text.secondary,
      "--ds-text-subtle": semanticThemeVars.color.text.tertiary,
      "--ds-text-faint": semanticThemeVars.color.text.muted,
      "--ds-text-fainter": semanticThemeVars.color.text.muted,
      "--ds-text-dim": semanticThemeVars.color.text.muted,
      "--ds-text-danger": semanticThemeVars.color.state.danger,
      "--ds-text-accent": semanticThemeVars.color.text.accent,
      "--ds-text-review-active": semanticThemeVars.color.text.primary,
      "--ds-text-review-done": semanticThemeVars.color.state.success,

      "--ds-brand-primary": semanticThemeVars.color.state.running,
      "--ds-brand-secondary": semanticThemeVars.color.text.accent,
      "--ds-brand-background": semanticThemeVars.color.bg.canvas,

      "--status-success": semanticThemeVars.color.state.success,
      "--status-warning": semanticThemeVars.color.state.warning,
      "--status-error": semanticThemeVars.color.state.danger,
      "--status-info": semanticThemeVars.color.state.info,
      "--select-caret": semanticThemeVars.color.icon.secondary,

      "--color-background": semanticThemeVars.color.bg.app,
      "--color-foreground": semanticThemeVars.color.text.primary,
      "--color-card": semanticThemeVars.color.bg.card,
      "--color-card-foreground": semanticThemeVars.color.text.primary,
      "--color-popover": semanticThemeVars.color.bg.elevated,
      "--color-popover-foreground": semanticThemeVars.color.text.primary,
      "--color-primary": semanticThemeVars.color.state.running,
      "--color-primary-foreground": semanticThemeVars.color.text.inverse,
      "--color-secondary": semanticThemeVars.color.control.default,
      "--color-secondary-foreground": semanticThemeVars.color.text.primary,
      "--color-muted": semanticThemeVars.color.bg.inset,
      "--color-muted-foreground": semanticThemeVars.color.text.secondary,
      "--color-accent": semanticThemeVars.color.control.hover,
      "--color-accent-foreground": semanticThemeVars.color.text.primary,
      "--color-destructive": semanticThemeVars.color.state.danger,
      "--color-destructive-foreground": semanticThemeVars.color.text.inverse,
      "--color-ring": semanticThemeVars.color.border.focus,
      "--color-border": semanticThemeVars.color.border.default,
      "--color-border-strong": semanticThemeVars.color.border.strong,
      "--color-input": semanticThemeVars.color.border.default,
      "--color-fg-primary": semanticThemeVars.color.text.primary,
      "--color-fg-secondary": semanticThemeVars.color.text.secondary,
      "--color-fg-tertiary": semanticThemeVars.color.text.tertiary,
      "--color-fg-inverted": semanticThemeVars.color.text.inverse,
      "--color-surface-0": semanticThemeVars.color.bg.card,
      "--color-surface-1": semanticThemeVars.color.bg.inset,
      "--color-surface-2": semanticThemeVars.color.bg.panel,
      "--color-surface-3": semanticThemeVars.color.bg.overlay,
      "--color-surface-elevated": semanticThemeVars.color.bg.elevated,
      "--color-surface-hover": semanticThemeVars.color.bg.hover,
      "--color-success": semanticThemeVars.color.state.success,
      "--color-success-foreground": semanticThemeVars.color.text.inverse,
      "--color-warning": semanticThemeVars.color.state.warning,
      "--color-warning-foreground": semanticThemeVars.color.text.inverse,
      "--color-info": semanticThemeVars.color.state.info,
      "--color-info-foreground": semanticThemeVars.color.text.inverse,
      "--color-error": semanticThemeVars.color.state.danger,
      "--color-error-foreground": semanticThemeVars.color.text.inverse,
      "--color-status-success": semanticThemeVars.color.state.success,
      "--color-status-warning": semanticThemeVars.color.state.warning,
      "--color-status-error": semanticThemeVars.color.state.danger,
      "--color-status-info": semanticThemeVars.color.state.info,
      "--color-success-subtle":
        "color-mix(in srgb, var(--color-success) 14%, var(--color-surface-1))",
      "--color-warning-subtle":
        "color-mix(in srgb, var(--color-warning) 14%, var(--color-surface-1))",
      "--color-destructive-subtle":
        "color-mix(in srgb, var(--color-destructive) 14%, var(--color-surface-1))",

      "--ds-scrollbar-track": "color-mix(in srgb, var(--ds-surface-app) 84%, transparent)",
      "--ds-scrollbar-thumb": "color-mix(in srgb, var(--ds-border-strong) 76%, transparent)",
      "--ds-scrollbar-thumb-hover":
        "color-mix(in srgb, var(--ds-border-strong) 92%, var(--ds-surface-control-hover))",

      "--ds-state-disabled-opacity": "0.56",
      "--ds-state-disabled-text": semanticThemeVars.color.text.disabled,
      "--ds-state-disabled-border": "color-mix(in srgb, var(--ds-border-subtle) 84%, transparent)",
      "--ds-state-disabled-bg": "color-mix(in srgb, var(--ds-surface-control) 42%, transparent)",
      "--ds-state-loading-ring":
        "color-mix(in srgb, var(--ds-border-accent-soft) 42%, transparent)",
      "--ds-state-loading-bg":
        "color-mix(in srgb, var(--ds-surface-control-hover) 72%, transparent)",
      "--ds-state-error-text": semanticThemeVars.color.state.danger,
      "--ds-state-error-border":
        "color-mix(in srgb, var(--ds-status-danger, var(--status-error)) 44%, transparent)",
      "--ds-state-error-bg":
        "color-mix(in srgb, var(--status-error) 12%, var(--ds-surface-card-base))",

      "--ds-input-focus-ring": semanticThemeVars.color.border.focus,
      "--ds-input-error-ring": "color-mix(in srgb, var(--status-error) 22%, transparent)",
      "--ds-hover-border-neutral": semanticThemeVars.color.border.default,

      "--ds-syntax-danger": semanticThemeVars.color.state.danger,
      "--ds-syntax-warning": semanticThemeVars.color.state.warning,
      "--ds-syntax-success": semanticThemeVars.color.state.success,
      "--ds-syntax-info": semanticThemeVars.color.state.info,
      "--ds-syntax-keyword": semanticThemeVars.color.text.accent,
      "--ds-syntax-function": semanticThemeVars.color.text.primary,
      "--ds-syntax-variable": semanticThemeVars.color.text.secondary,

      "--ds-modal-backdrop": semanticThemeVars.color.overlay.scrim,
      "--ds-modal-backdrop-blur": semanticThemeVars.motion.blur.overlay,
      "--ds-modal-card-bg": semanticThemeVars.color.bg.overlay,
      "--ds-modal-card-border": semanticThemeVars.color.border.default,
      "--ds-modal-card-radius": semanticThemeVars.radius.x2,
      "--ds-modal-card-shadow": semanticThemeVars.shadow.overlay,
      "--ds-modal-focus-ring": semanticThemeVars.color.border.focus,

      "--ds-toast-bg": semanticThemeVars.color.bg.overlay,
      "--ds-toast-border": semanticThemeVars.color.border.default,
      "--ds-toast-shadow": semanticThemeVars.shadow.lg,
      "--ds-toast-radius": semanticThemeVars.radius.xl,
      "--ds-toast-title": semanticThemeVars.color.text.secondary,
      "--ds-toast-body": semanticThemeVars.color.text.primary,
      "--ds-toast-enter-y": "-4px",

      "--ds-panel-gap": semanticThemeVars.space.md,
      "--ds-panel-header-min-height": semanticThemeVars.size.control.sm,
      "--ds-panel-header-text": "var(--text-panel-label)",
      "--ds-panel-border": "var(--border-panel)",
      "--ds-panel-surface": semanticThemeVars.color.bg.panel,
      "--ds-panel-bg": "var(--surface-right-panel)",
      "--ds-panel-header-bg":
        "color-mix(in srgb, var(--surface-panel-header) 96%, var(--surface-right-panel))",
      "--ds-panel-section-bg": "var(--surface-panel-section)",
      "--ds-panel-section-divider": "var(--border-panel-divider)",
      "--ds-panel-title": "var(--text-panel-title)",
      "--ds-panel-subtitle": "var(--text-panel-subtitle)",
      "--ds-panel-label": "var(--text-panel-label)",
      "--ds-panel-muted": "var(--text-panel-muted)",
      "--ds-panel-value": "var(--text-panel-value)",
      "--ds-panel-row-hover": "var(--surface-panel-row-hover)",
      "--ds-panel-row-selected": "var(--surface-panel-row-selected)",
      "--ds-panel-highlight": "var(--surface-panel-highlight)",
      "--ds-panel-code-bg": "var(--surface-panel-code)",
      "--ds-panel-log-bg": "var(--surface-panel-log)",
      "--ds-panel-diff-add-bg": "var(--surface-panel-diff-add)",
      "--ds-panel-diff-remove-bg": "var(--surface-panel-diff-remove)",
      "--ds-panel-footer-border": "var(--border-panel-sticky)",
      "--ds-panel-footer-shadow": "var(--shadow-panel-sticky)",
      "--ds-panel-resize-handle":
        "color-mix(in srgb, var(--border-panel-resize-handle) 82%, transparent)",
      "--ds-panel-focus-ring": "var(--focus-panel-ring)",

      "--ds-popover-bg": semanticThemeVars.color.bg.elevated,
      "--ds-popover-border": semanticThemeVars.color.border.default,
      "--ds-popover-shadow": semanticThemeVars.shadow.lg,
      "--ds-popover-radius": semanticThemeVars.radius.xl,
      "--ds-popover-item-text": semanticThemeVars.color.text.secondary,
      "--ds-popover-item-text-active": semanticThemeVars.color.text.primary,

      "--ds-button-height-sm": semanticThemeVars.size.control.sm,
      "--ds-button-height-md": semanticThemeVars.size.control.md,
      "--ds-button-height-lg": semanticThemeVars.size.control.lg,
      "--ds-button-padding-sm": "0 12px",
      "--ds-button-padding-md": "0 15px",
      "--ds-button-padding-lg": "0 20px",
      "--ds-button-font-sm": semanticThemeVars.typography.size.md,
      "--ds-button-font-md": semanticThemeVars.typography.size.lg,
      "--ds-button-font-lg": semanticThemeVars.typography.size.xl,
      "--ds-button-gap-sm": semanticThemeVars.space.xs,
      "--ds-button-gap-md": semanticThemeVars.space.sm,
      "--ds-button-gap-lg": semanticThemeVars.space.sm,
      "--ds-button-bg-primary": semanticThemeVars.color.state.running,
      "--ds-button-fg-primary": semanticThemeVars.color.text.inverse,
      "--ds-button-bg-secondary": semanticThemeVars.color.control.default,
      "--ds-button-fg-secondary": semanticThemeVars.color.text.primary,
      "--ds-button-border-secondary": semanticThemeVars.color.border.default,
      "--ds-button-bg-ghost": "transparent",
      "--ds-button-fg-ghost": semanticThemeVars.color.text.secondary,
      "--ds-button-bg-danger": semanticThemeVars.color.state.danger,
      "--ds-button-fg-danger": semanticThemeVars.color.text.inverse,

      "--ds-input-height": semanticThemeVars.size.control.lg,
      "--ds-input-padding": "11px 14px",
      "--ds-input-font": semanticThemeVars.typography.size.xl,
      "--ds-input-surface": semanticThemeVars.color.bg.input,
      "--ds-input-border": semanticThemeVars.color.border.default,
      "--ds-input-text": semanticThemeVars.color.text.primary,
      "--ds-input-placeholder": semanticThemeVars.color.text.tertiary,

      "--ds-card-padding-sm": "14px",
      "--ds-card-padding-md": "18px",
      "--ds-card-padding-lg": "22px",
      "--ds-card-border": semanticThemeVars.color.border.default,
      "--ds-card-surface": semanticThemeVars.color.bg.card,
      "--ds-card-surface-muted": semanticThemeVars.color.bg.inset,

      "--ds-select-radius": semanticThemeVars.radius.md,
      "--ds-select-trigger-height": semanticThemeVars.size.control.sm,
      "--ds-select-menu-max-height": "280px",

      "--ds-sidebar-width": semanticThemeVars.size.layout.sidebar,
      "--ds-sidebar-width-compact": semanticThemeVars.size.layout.sidebarCompact,
      "--ds-sidebar-rail-width": semanticThemeVars.size.layout.sidebarRail,
      "--ds-inspector-width": semanticThemeVars.size.layout.inspector,
      "--ds-composer-max-width": semanticThemeVars.size.layout.composerMaxWidth,
      "--ds-composer-min-height": semanticThemeVars.size.layout.composerMinHeight,
      "--ds-content-max-width": semanticThemeVars.size.layout.contentMaxWidth,

      "--ds-shell-control-border": semanticThemeVars.color.border.default,
      "--ds-shell-control-border-hover": semanticThemeVars.color.border.strong,
      "--ds-shell-control-border-active": semanticThemeVars.color.border.accent,
      "--ds-shell-control-bg": semanticThemeVars.color.control.default,
      "--ds-shell-control-bg-hover": semanticThemeVars.color.control.hover,
      "--ds-shell-control-bg-active": semanticThemeVars.color.control.pressed,
      "--ds-shell-control-shadow":
        "inset 0 1px 0 color-mix(in srgb, var(--ds-color-white) 6%, transparent)",
      "--ds-shell-control-shadow-hover":
        "inset 0 1px 0 color-mix(in srgb, var(--ds-color-white) 8%, transparent), var(--ds-shadow-xs)",
      "--ds-shell-control-focus-outline":
        "2px solid color-mix(in srgb, var(--ds-focus-ring) 72%, transparent)",
      "--ds-shell-control-focus-shadow":
        "0 0 0 1px color-mix(in srgb, var(--ds-focus-ring) 30%, transparent)",

      "--ds-status-running": semanticThemeVars.color.state.running,
      "--ds-status-queued": semanticThemeVars.color.state.queued,
      "--ds-status-thinking": semanticThemeVars.color.state.thinking,
      "--ds-status-streaming": semanticThemeVars.color.state.streaming,
      "--ds-status-success": semanticThemeVars.color.state.success,
      "--ds-status-warning": semanticThemeVars.color.state.warning,
      "--ds-status-danger": semanticThemeVars.color.state.danger,
      "--ds-status-info": semanticThemeVars.color.state.info,
      "--ds-status-cancelled": semanticThemeVars.color.state.cancelled,
      "--ds-status-offline": semanticThemeVars.color.state.offline,

      "--ds-diff-insert-bg": semanticThemeVars.color.diff.insertBg,
      "--ds-diff-insert-border": semanticThemeVars.color.diff.insertBorder,
      "--ds-diff-delete-bg": semanticThemeVars.color.diff.deleteBg,
      "--ds-diff-delete-border": semanticThemeVars.color.diff.deleteBorder,
      "--ds-diff-modified-bg": semanticThemeVars.color.diff.modifiedBg,
      "--ds-diff-modified-border": semanticThemeVars.color.diff.modifiedBorder,
      "--ds-diff-gutter": semanticThemeVars.color.diff.gutter,
      "--ds-diff-inline-highlight": semanticThemeVars.color.diff.inlineHighlight,
    },
  },
} as unknown as import("@vanilla-extract/css").GlobalStyleRule);
