import type { MainAppLayoutShellBridgeDomainInput } from "./types";

export function buildMainAppLayoutShellBridgeInput(input: MainAppLayoutShellBridgeDomainInput) {
  const {
    state: {
      mainAppHandlers,
      appSettings,
      workspaceGroupsCount,
      launchScriptState,
      sidebarToggleProps,
      activeTab,
      showPollingFetchStatus,
      pollingIntervalMs,
      activeGitRoot,
      worktreeApplyLoading,
      worktreeApplyError,
      worktreeApplySuccess,
      threadsState,
      workspacesById,
      workspaces,
      groupedWorkspaces,
      hasLoadedWorkspaces,
      workspaceLoadError,
      deletingWorktreeIds,
      newAgentDraftWorkspaceId,
      startingDraftThreadWorkspaceId,
      threadListSortKey,
      activeWorkspaceId,
      openAppIconById,
      activeWorkspace,
      onOpenBranchSwitcher,
      handleBranchSelection,
      launchScriptsState,
      activeAtlasDriverOrder,
      activeAtlasEnabled,
      activeAtlasDetailLevel,
      activeAtlasLongTermMemoryDigest,
      fileStatus,
      gitRemoteUrl,
      gitRootCandidates,
      gitRootScanDepth,
      gitRootScanLoading,
      gitRootScanError,
      gitRootScanHasScanned,
      conversationState: { homeState, composerState },
      gitPanelState,
      gitHubPanelState,
      layoutState,
    },
    actions: {
      handleSetThreadListSortKey,
      handleRefreshAllWorkspaceThreads,
      onOpenSettings,
      clearDraftState,
      clearDraftStateIfDifferentWorkspace,
      selectHome,
      selectWorkspace,
      connectWorkspace,
      setActiveTab,
      updateWorkspaceSettings,
      handleRenameThread,
      removeWorkspace,
      removeWorktree,
      exitDiffView,
      refreshGitStatus,
      handleCopyThread,
      onActiveAtlasDriverOrderChange,
      onActiveAtlasEnabledChange,
      onActiveAtlasDetailLevelChange,
      setGitRootScanDepth,
      scanGitRoots,
      handlePickGitRoot,
      handleSetGitRoot,
      handleApplyWorktreeChanges,
      handleStageGitAll,
      handleStageGitFile,
      handleUnstageGitFile,
      handleRevertGitFile,
      handleRevertAllGitChanges,
    },
  } = input;

  return {
    mainAppHandlers,
    workspaceGroupsCount,
    appSettings,
    handleSetThreadListSortKey,
    handleRefreshAllWorkspaceThreads,
    onOpenSettings,
    clearDraftState,
    clearDraftStateIfDifferentWorkspace,
    selectHome,
    selectWorkspace,
    connectWorkspace,
    setActiveTab,
    workspacesById,
    updateWorkspaceSettings,
    clearDraftForThread: composerState.clearDraftForThread,
    removeImagesForThread: composerState.removeImagesForThread,
    handleRenameThread,
    removeWorkspace,
    removeWorktree,
    refreshLocalUsage: homeState.refreshLocalUsage,
    launchScriptState,
    setGitDiffViewStyle: gitPanelState.setGitDiffViewStyle,
    sidebarToggleProps,
    rightPanelCollapsed: layoutState.rightPanelCollapsed,
    exitDiffView,
    setCenterMode: gitPanelState.setCenterMode,
    setSelectedDiffPath: gitPanelState.setSelectedDiffPath,
    selectedPullRequestCandidate: gitPanelState.selectedPullRequest,
    selectedPullRequestCommentsAll: gitHubPanelState.gitPullRequestComments,
    setSelectedCommitSha: gitPanelState.setSelectedCommitSha,
    handleSelectCommitSha: gitPanelState.handleSelectCommit,
    activeGitRoot,
    handleSetGitRoot,
    prefillDraft: composerState.prefillDraft,
    setPrefillDraft: composerState.setPrefillDraft,
    composerInsert: composerState.composerInsert,
    setComposerInsert: composerState.setComposerInsert,
    isCompact: layoutState.isCompact,
    isPhone: layoutState.isPhone,
    worktreeApplyLoadingState: worktreeApplyLoading,
    worktreeApplyErrorState: worktreeApplyError,
    worktreeApplySuccessState: worktreeApplySuccess,
    handleApplyWorktreeChanges,
    ...threadsState,
    workspaces,
    groupedWorkspaces,
    hasLoadedWorkspaces,
    workspaceLoadError,
    deletingWorktreeIds,
    newAgentDraftWorkspaceId,
    startingDraftThreadWorkspaceId,
    threadListSortKey,
    activeWorkspaceId,
    openAppIconById,
    activeWorkspace,
    onOpenBranchSwitcher,
    onSelectBranchWorkflowSelection: handleBranchSelection,
    onRefreshGitStatus: refreshGitStatus,
    onCopyThread: handleCopyThread,
    onToggleTerminal: layoutState.handleToggleTerminal,
    launchScriptsState,
    atlasDriverOrder: activeAtlasDriverOrder,
    atlasEnabled: activeAtlasEnabled,
    atlasDetailLevel: activeAtlasDetailLevel,
    atlasLongTermMemoryDigest: activeAtlasLongTermMemoryDigest,
    onAtlasDriverOrderChange: onActiveAtlasDriverOrderChange,
    onAtlasEnabledChange: onActiveAtlasEnabledChange,
    onAtlasDetailLevelChange: onActiveAtlasDetailLevelChange,
    fileStatus,
    gitRemoteUrl,
    gitRootCandidates,
    gitRootScanDepth,
    gitRootScanLoading,
    gitRootScanError,
    gitRootScanHasScanned,
    onGitRootScanDepthChange: setGitRootScanDepth,
    onScanGitRoots: scanGitRoots,
    onPickGitRoot: handlePickGitRoot,
    onStageGitAll: handleStageGitAll,
    onStageGitFile: handleStageGitFile,
    onUnstageGitFile: handleUnstageGitFile,
    onRevertGitFile: handleRevertGitFile,
    onRevertAllGitChanges: handleRevertAllGitChanges,
    activeTab,
    showPollingFetchStatus,
    pollingIntervalMs,
  };
}
