import type { MainAppLayoutRuntimeBridgeDomainInput } from "./types";

export function buildMainAppRuntimeAndNotificationsBridgeInput(
  input: MainAppLayoutRuntimeBridgeDomainInput
) {
  const {
    state: {
      activeAccount,
      accountSwitching,
      accountSwitchError,
      accountCenter,
      canRefreshCurrentUsage,
      canRefreshAllUsage,
      currentUsageRefreshLoading,
      allUsageRefreshLoading,
      errorToasts,
      debugState,
      layoutState,
      updaterController,
      terminalControls,
    },
    actions: {
      handleSwitchAccount,
      handleSelectLoggedInCodexAccount,
      handleCancelSwitchAccount,
      onConnectLocalRuntimePort,
      onRefreshCurrentUsage,
      onRefreshAllUsage,
      handleSelectOpenAppId,
      dismissErrorToast,
    },
  } = input;

  return {
    activeAccount,
    handleSwitchAccount,
    handleSelectLoggedInCodexAccount,
    handleCancelSwitchAccount,
    onConnectLocalRuntimePort,
    accountSwitching,
    accountSwitchError,
    accountCenter,
    onRefreshCurrentUsage,
    onRefreshAllUsage,
    canRefreshCurrentUsage,
    canRefreshAllUsage,
    currentUsageRefreshLoading,
    allUsageRefreshLoading,
    onSelectOpenAppId: handleSelectOpenAppId,
    onOpenDebug: layoutState.handleDebugClick,
    showDebugButton: debugState.showDebugButton,
    updaterState: updaterController.updaterState,
    onUpdate: updaterController.startUpdate,
    onDismissUpdate: updaterController.dismissUpdate,
    postUpdateNotice: updaterController.postUpdateNotice,
    onDismissPostUpdateNotice: updaterController.dismissPostUpdateNotice,
    errorToasts,
    onDismissErrorToast: dismissErrorToast,
    debugEntries: debugState.debugEntries,
    debugOpen: debugState.debugOpen,
    terminalOpen: layoutState.terminalOpen,
    terminalTabs: terminalControls.terminalTabs,
    activeTerminalId: terminalControls.activeTerminalId,
    onSelectTerminal: terminalControls.onSelectTerminal,
    onNewTerminal: terminalControls.onNewTerminal,
    onCloseTerminal: terminalControls.onCloseTerminal,
    onClearTerminal: terminalControls.handleClearActiveTerminal,
    onRestartTerminal: terminalControls.handleRestartActiveTerminal,
    onInterruptTerminal: terminalControls.handleInterruptActiveTerminal,
    canClearTerminal: terminalControls.canControlActiveTerminal,
    canRestartTerminal: terminalControls.canControlActiveTerminal,
    canInterruptTerminal: terminalControls.canControlActiveTerminal,
    terminalState: terminalControls.terminalState,
    onClearDebug: debugState.clearDebugEntries,
    onCopyDebug: debugState.handleCopyDebug,
    onResizeDebug: layoutState.onDebugPanelResizeStart,
    onResizeTerminal: layoutState.onTerminalPanelResizeStart,
  };
}
