import type { ConversationItem, ThreadListSortKey, ThreadSummary } from "../../../types";
import { looksAutoGeneratedThreadName } from "../utils/threadTitle";

const MAX_THREAD_NAME_LENGTH = 38;

export { looksAutoGeneratedThreadName };

function formatThreadName(text: string) {
  const trimmed = text.trim();
  if (!trimmed) {
    return null;
  }
  return trimmed.length > MAX_THREAD_NAME_LENGTH
    ? `${trimmed.slice(0, MAX_THREAD_NAME_LENGTH)}…`
    : trimmed;
}

export function extractRenameText(text: string) {
  if (!text) {
    return "";
  }
  const withoutImages = text.replace(/\[image(?: x\d+)?\]/gi, " ");
  const withoutSkills = withoutImages.replace(/(^|\s)\$[A-Za-z0-9_-]+(?=\s|$)/g, " ");
  return withoutSkills.replace(/\s+/g, " ").trim();
}

function isOptimisticUserMessage(item: ConversationItem) {
  return item.kind === "message" && item.role === "user" && item.id.startsWith("optimistic-user-");
}

function normalizeUserMessageText(text: string) {
  return text.trim().replace(/\s+/g, " ");
}

function areMatchingUserMessages(left: ConversationItem, right: ConversationItem) {
  if (
    left.kind !== "message" ||
    left.role !== "user" ||
    right.kind !== "message" ||
    right.role !== "user"
  ) {
    return false;
  }
  if (normalizeUserMessageText(left.text) !== normalizeUserMessageText(right.text)) {
    return false;
  }
  const leftImages = left.images ?? [];
  const rightImages = right.images ?? [];
  if (leftImages.length !== rightImages.length) {
    return false;
  }
  return leftImages.every((image, index) => image === rightImages[index]);
}

export function reconcileOptimisticUserMessage(
  list: ConversationItem[],
  incoming: ConversationItem
) {
  if (
    incoming.kind !== "message" ||
    incoming.role !== "user" ||
    incoming.id.startsWith("optimistic-user-")
  ) {
    return list;
  }
  for (let index = list.length - 1; index >= 0; index -= 1) {
    const candidate = list[index];
    if (!isOptimisticUserMessage(candidate)) {
      continue;
    }
    if (!areMatchingUserMessages(candidate, incoming)) {
      continue;
    }
    const next = [...list];
    next.splice(index, 1);
    return next;
  }
  return list;
}

function getAssistantTextForRename(items: ConversationItem[], itemId?: string): string {
  if (itemId) {
    const match = items.find(
      (item) => item.kind === "message" && item.role === "assistant" && item.id === itemId
    );
    if (match && match.kind === "message") {
      return match.text;
    }
  }
  for (let index = items.length - 1; index >= 0; index -= 1) {
    const item = items[index];
    if (item.kind === "message" && item.role === "assistant") {
      return item.text;
    }
  }
  return "";
}

export function maybeRenameThreadFromAgent({
  workspaceId,
  threadId,
  items,
  itemId,
  hasCustomName,
  threadsByWorkspace,
}: {
  workspaceId: string;
  threadId: string;
  items: ConversationItem[];
  itemId?: string;
  hasCustomName: boolean;
  threadsByWorkspace: Record<string, ThreadSummary[]>;
}) {
  const threads = threadsByWorkspace[workspaceId] ?? [];
  if (!threads.length) {
    return threadsByWorkspace;
  }
  const hasUserMessage = items.some((item) => item.kind === "message" && item.role === "user");
  if (hasUserMessage) {
    return threadsByWorkspace;
  }
  if (hasCustomName) {
    return threadsByWorkspace;
  }
  const nextName = formatThreadName(getAssistantTextForRename(items, itemId));
  if (!nextName) {
    return threadsByWorkspace;
  }
  let didChange = false;
  const nextThreads = threads.map((thread) => {
    if (
      thread.id !== threadId ||
      thread.name === nextName ||
      !looksAutoGeneratedThreadName(thread.name)
    ) {
      return thread;
    }
    didChange = true;
    return { ...thread, name: nextName };
  });
  return didChange ? { ...threadsByWorkspace, [workspaceId]: nextThreads } : threadsByWorkspace;
}

export function mergeStreamingText(existing: string, delta: string) {
  if (!delta) {
    return existing;
  }
  if (!existing) {
    return delta;
  }
  if (delta === existing) {
    return existing;
  }
  if (delta.startsWith(existing)) {
    return delta;
  }
  if (existing.startsWith(delta)) {
    return existing;
  }
  const maxOverlap = Math.min(existing.length, delta.length);
  for (let length = maxOverlap; length > 0; length -= 1) {
    if (existing.endsWith(delta.slice(0, length))) {
      return `${existing}${delta.slice(length)}`;
    }
  }
  return `${existing}${delta}`;
}

export function addSummaryBoundary(existing: string) {
  if (!existing) {
    return existing;
  }
  if (existing.endsWith("\n\n")) {
    return existing;
  }
  if (existing.endsWith("\n")) {
    return `${existing}\n`;
  }
  return `${existing}\n\n`;
}

export function dropLatestLocalReviewStart(list: ConversationItem[]) {
  for (let index = list.length - 1; index >= 0; index -= 1) {
    const item = list[index];
    if (item.kind === "review" && item.state === "started" && item.id.startsWith("review-start-")) {
      return [...list.slice(0, index), ...list.slice(index + 1)];
    }
  }
  return list;
}

export function findMatchingReview(
  list: ConversationItem[],
  target: Extract<ConversationItem, { kind: "review" }>
) {
  const normalizedText = target.text.trim();
  return list.find(
    (item) =>
      item.kind === "review" && item.state === target.state && item.text.trim() === normalizedText
  );
}

export function ensureUniqueReviewId(list: ConversationItem[], item: ConversationItem) {
  if (item.kind !== "review") {
    return item;
  }
  if (!list.some((entry) => entry.id === item.id)) {
    return item;
  }
  const existingIds = new Set(list.map((entry) => entry.id));
  let suffix = 1;
  let candidate = `${item.id}-${suffix}`;
  while (existingIds.has(candidate)) {
    suffix += 1;
    candidate = `${item.id}-${suffix}`;
  }
  return { ...item, id: candidate };
}

export function isDuplicateReviewById(
  list: ConversationItem[],
  target: Extract<ConversationItem, { kind: "review" }>
) {
  const normalizedText = target.text.trim();
  return list.some(
    (item) =>
      item.kind === "review" &&
      item.id === target.id &&
      item.state === target.state &&
      item.text.trim() === normalizedText
  );
}

export function prefersUpdatedSort(
  threadSortKeyByWorkspace: Record<string, ThreadListSortKey>,
  workspaceId: string
) {
  return (threadSortKeyByWorkspace[workspaceId] ?? "updated_at") === "updated_at";
}
