import type { ConversationItem, ThreadSummary } from "../../../types";
import { normalizeItem, prepareThreadItems, upsertItem } from "../../../utils/threadItems";
import { normalizeLifecycleStatus } from "../../../utils/lifecycleStatus";
import {
  addSummaryBoundary,
  dropLatestLocalReviewStart,
  ensureUniqueReviewId,
  extractRenameText,
  findMatchingReview,
  isDuplicateReviewById,
  looksAutoGeneratedThreadName,
  maybeRenameThreadFromAgent,
  mergeStreamingText,
  prefersUpdatedSort,
  reconcileOptimisticUserMessage,
} from "./useThreadsReducer.helpers";
import {
  initialState,
  type ThreadAction,
  type ThreadActivityStatus,
  type ThreadState,
} from "./useThreadsReducer.types";

export { initialState };
export type { ThreadAction, ThreadState };

type MarkProcessingAction = Extract<ThreadAction, { type: "markProcessing" }>;
type MarkImmediateCompletionAction = Extract<ThreadAction, { type: "markImmediateCompletion" }>;
type HydrateThreadStatusAction = Extract<ThreadAction, { type: "hydrateThreadStatus" }>;

function hasSameThreadActivityStatus(
  previous: ThreadActivityStatus | undefined,
  next: ThreadActivityStatus
): boolean {
  if (!previous) {
    return false;
  }
  return (
    previous.isProcessing === next.isProcessing &&
    previous.hasUnread === next.hasUnread &&
    previous.isReviewing === next.isReviewing &&
    previous.executionState === next.executionState &&
    previous.processingStartedAt === next.processingStartedAt &&
    previous.lastDurationMs === next.lastDurationMs
  );
}

function reduceMarkProcessing(state: ThreadState, action: MarkProcessingAction): ThreadState {
  const previous = state.threadStatusById[action.threadId];
  const wasProcessing = previous?.isProcessing ?? false;
  const startedAt = previous?.processingStartedAt ?? null;
  const lastDurationMs = previous?.lastDurationMs ?? null;
  const hasUnread = previous?.hasUnread ?? false;
  const isReviewing = previous?.isReviewing ?? false;
  const previousExecutionState = previous?.executionState ?? (wasProcessing ? "running" : "idle");
  if (action.isProcessing) {
    const nextStartedAt = wasProcessing && startedAt ? startedAt : action.timestamp;
    const nextExecutionState =
      action.executionState ??
      (previousExecutionState === "awaitingApproval" ? "awaitingApproval" : "running");
    const nextStatus: ThreadActivityStatus = {
      isProcessing: true,
      hasUnread,
      isReviewing,
      executionState: nextExecutionState,
      processingStartedAt: nextStartedAt,
      lastDurationMs,
    };
    if (hasSameThreadActivityStatus(previous, nextStatus)) {
      return state;
    }
    return {
      ...state,
      threadStatusById: {
        ...state.threadStatusById,
        [action.threadId]: nextStatus,
      },
    };
  }
  const nextDuration =
    wasProcessing && startedAt
      ? Math.max(0, action.timestamp - startedAt)
      : (lastDurationMs ?? null);
  const nextStatus: ThreadActivityStatus = {
    isProcessing: false,
    hasUnread,
    isReviewing,
    executionState: "idle",
    processingStartedAt: null,
    lastDurationMs: nextDuration,
  };
  if (hasSameThreadActivityStatus(previous, nextStatus)) {
    return state;
  }
  return {
    ...state,
    threadStatusById: {
      ...state.threadStatusById,
      [action.threadId]: nextStatus,
    },
  };
}

function reduceMarkImmediateCompletion(
  state: ThreadState,
  action: MarkImmediateCompletionAction
): ThreadState {
  const previous = state.threadStatusById[action.threadId];
  const nextStatus: ThreadActivityStatus = {
    isProcessing: false,
    hasUnread: previous?.hasUnread ?? false,
    isReviewing: previous?.isReviewing ?? false,
    executionState: "idle",
    processingStartedAt: null,
    lastDurationMs: 0,
  };
  if (hasSameThreadActivityStatus(previous, nextStatus)) {
    return state;
  }
  return {
    ...state,
    threadStatusById: {
      ...state.threadStatusById,
      [action.threadId]: nextStatus,
    },
  };
}

function reduceHydrateThreadStatus(
  state: ThreadState,
  action: HydrateThreadStatusAction
): ThreadState {
  const previous = state.threadStatusById[action.threadId];
  const nextStatus: ThreadActivityStatus = {
    isProcessing: false,
    hasUnread: previous?.hasUnread ?? false,
    isReviewing: previous?.isReviewing ?? false,
    executionState: "idle",
    processingStartedAt: null,
    lastDurationMs: action.lastDurationMs,
  };
  if (hasSameThreadActivityStatus(previous, nextStatus)) {
    return state;
  }
  return {
    ...state,
    threadStatusById: {
      ...state.threadStatusById,
      [action.threadId]: nextStatus,
    },
  };
}

function completePendingTurnItems(items: ConversationItem[]): ConversationItem[] {
  let changed = false;
  const next = [...items];
  for (let index = next.length - 1; index >= 0; index -= 1) {
    const item = next[index];
    if (item.kind === "message" && item.role === "user") {
      break;
    }
    if (item.kind !== "tool") {
      continue;
    }
    if (normalizeLifecycleStatus(item.status) !== "inProgress") {
      continue;
    }
    next[index] = {
      ...item,
      status: "completed",
    };
    changed = true;
  }
  return changed ? prepareThreadItems(next) : items;
}

export function threadReducer(state: ThreadState, action: ThreadAction): ThreadState {
  switch (action.type) {
    case "setActiveThreadId":
      return {
        ...state,
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: action.threadId,
        },
        threadStatusById: action.threadId
          ? {
              ...state.threadStatusById,
              [action.threadId]: {
                isProcessing: state.threadStatusById[action.threadId]?.isProcessing ?? false,
                hasUnread: false,
                isReviewing: state.threadStatusById[action.threadId]?.isReviewing ?? false,
                executionState:
                  state.threadStatusById[action.threadId]?.executionState ??
                  (state.threadStatusById[action.threadId]?.isProcessing ? "running" : "idle"),
                processingStartedAt:
                  state.threadStatusById[action.threadId]?.processingStartedAt ?? null,
                lastDurationMs: state.threadStatusById[action.threadId]?.lastDurationMs ?? null,
              },
            }
          : state.threadStatusById,
      };
    case "ensureThread": {
      const hidden =
        state.hiddenThreadIdsByWorkspace[action.workspaceId]?.[action.threadId] ?? false;
      if (hidden) {
        return state;
      }
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      if (list.some((thread) => thread.id === action.threadId)) {
        return state;
      }
      const thread: ThreadSummary = {
        id: action.threadId,
        name: "New Agent",
        updatedAt: 0,
      };
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: [thread, ...list],
        },
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: {
            isProcessing: false,
            hasUnread: false,
            isReviewing: false,
            executionState: "idle",
            processingStartedAt: null,
            lastDurationMs: null,
          },
        },
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]:
            state.activeThreadIdByWorkspace[action.workspaceId] ?? action.threadId,
        },
      };
    }
    case "markImmediateCompletion":
      return reduceMarkImmediateCompletion(state, action);
    case "hydrateThreadStatus":
      return reduceHydrateThreadStatus(state, action);
    case "hideThread": {
      const hiddenForWorkspace = state.hiddenThreadIdsByWorkspace[action.workspaceId] ?? {};
      if (hiddenForWorkspace[action.threadId]) {
        return state;
      }

      const nextHiddenForWorkspace = {
        ...hiddenForWorkspace,
        [action.threadId]: true as const,
      };

      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const filtered = list.filter((thread) => thread.id !== action.threadId);
      const nextActive =
        state.activeThreadIdByWorkspace[action.workspaceId] === action.threadId
          ? (filtered[0]?.id ?? null)
          : (state.activeThreadIdByWorkspace[action.workspaceId] ?? null);

      return {
        ...state,
        hiddenThreadIdsByWorkspace: {
          ...state.hiddenThreadIdsByWorkspace,
          [action.workspaceId]: nextHiddenForWorkspace,
        },
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: filtered,
        },
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: nextActive,
        },
      };
    }
    case "removeThread": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const filtered = list.filter((thread) => thread.id !== action.threadId);
      const nextActive =
        state.activeThreadIdByWorkspace[action.workspaceId] === action.threadId
          ? (filtered[0]?.id ?? null)
          : (state.activeThreadIdByWorkspace[action.workspaceId] ?? null);
      const { [action.threadId]: _, ...restItems } = state.itemsByThread;
      const { [action.threadId]: __, ...restStatus } = state.threadStatusById;
      const { [action.threadId]: ___, ...restTurns } = state.activeTurnIdByThread;
      const { [action.threadId]: ____, ...restDiffs } = state.turnDiffByThread;
      const { [action.threadId]: _____, ...restPlans } = state.planByThread;
      const { [action.threadId]: ______, ...restParents } = state.threadParentById;
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: filtered,
        },
        itemsByThread: restItems,
        threadStatusById: restStatus,
        activeTurnIdByThread: restTurns,
        turnDiffByThread: restDiffs,
        planByThread: restPlans,
        threadParentById: restParents,
        activeThreadIdByWorkspace: {
          ...state.activeThreadIdByWorkspace,
          [action.workspaceId]: nextActive,
        },
      };
    }
    case "setThreadParent": {
      if (!action.parentId || action.parentId === action.threadId) {
        return state;
      }
      if (state.threadParentById[action.threadId] === action.parentId) {
        return state;
      }
      return {
        ...state,
        threadParentById: {
          ...state.threadParentById,
          [action.threadId]: action.parentId,
        },
      };
    }
    case "markProcessing":
      return reduceMarkProcessing(state, action);
    case "setActiveTurnId":
      return {
        ...state,
        activeTurnIdByThread: {
          ...state.activeTurnIdByThread,
          [action.threadId]: action.turnId,
        },
      };
    case "markReviewing": {
      const previous = state.threadStatusById[action.threadId];
      const nextStatus: ThreadActivityStatus = {
        isProcessing: previous?.isProcessing ?? false,
        hasUnread: previous?.hasUnread ?? false,
        isReviewing: action.isReviewing,
        executionState: previous?.executionState,
        processingStartedAt: previous?.processingStartedAt ?? null,
        lastDurationMs: previous?.lastDurationMs ?? null,
      };
      if (
        previous &&
        previous.isProcessing === nextStatus.isProcessing &&
        previous.hasUnread === nextStatus.hasUnread &&
        previous.isReviewing === nextStatus.isReviewing &&
        previous.executionState === nextStatus.executionState &&
        previous.processingStartedAt === nextStatus.processingStartedAt &&
        previous.lastDurationMs === nextStatus.lastDurationMs
      ) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: nextStatus,
        },
      };
    }
    case "markUnread": {
      const previous = state.threadStatusById[action.threadId];
      const nextStatus: ThreadActivityStatus = {
        isProcessing: previous?.isProcessing ?? false,
        hasUnread: action.hasUnread,
        isReviewing: previous?.isReviewing ?? false,
        executionState: previous?.executionState,
        processingStartedAt: previous?.processingStartedAt ?? null,
        lastDurationMs: previous?.lastDurationMs ?? null,
      };
      if (
        previous &&
        previous.isProcessing === nextStatus.isProcessing &&
        previous.hasUnread === nextStatus.hasUnread &&
        previous.isReviewing === nextStatus.isReviewing &&
        previous.executionState === nextStatus.executionState &&
        previous.processingStartedAt === nextStatus.processingStartedAt &&
        previous.lastDurationMs === nextStatus.lastDurationMs
      ) {
        return state;
      }
      return {
        ...state,
        threadStatusById: {
          ...state.threadStatusById,
          [action.threadId]: nextStatus,
        },
      };
    }
    case "addAssistantMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const message: ConversationItem = {
        id: `${Date.now()}-assistant`,
        kind: "message",
        role: "assistant",
        text: action.text,
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems([...list, message]),
        },
      };
    }
    case "setThreadName": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      const next = list.map((thread) =>
        thread.id === action.threadId ? { ...thread, name: action.name } : thread
      );
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: next,
        },
      };
    }
    case "setThreadTimestamp": {
      const list = state.threadsByWorkspace[action.workspaceId] ?? [];
      if (!list.length) {
        return state;
      }
      let didChange = false;
      const next = list.map((thread) => {
        if (thread.id !== action.threadId) {
          return thread;
        }
        const current = thread.updatedAt ?? 0;
        if (current >= action.timestamp) {
          return thread;
        }
        didChange = true;
        return { ...thread, updatedAt: action.timestamp };
      });
      if (!didChange) {
        return state;
      }
      const sorted = prefersUpdatedSort(state.threadSortKeyByWorkspace, action.workspaceId)
        ? [
            ...next.filter((thread) => thread.id === action.threadId),
            ...next.filter((thread) => thread.id !== action.threadId),
          ]
        : next;
      return {
        ...state,
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: sorted,
        },
      };
    }
    case "appendAgentDelta": {
      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      const index = list.findIndex((msg) => msg.id === action.itemId);
      if (index >= 0 && list[index].kind === "message") {
        const existing = list[index];
        list[index] = {
          ...existing,
          text: mergeStreamingText(existing.text, action.delta),
        };
      } else {
        list.push({
          id: action.itemId,
          kind: "message",
          role: "assistant",
          text: action.delta,
        });
      }
      const updatedItems = prepareThreadItems(list);
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "completeAgentMessage": {
      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      const index = list.findIndex((msg) => msg.id === action.itemId);
      if (index >= 0 && list[index].kind === "message") {
        const existing = list[index];
        list[index] = {
          ...existing,
          text: action.text || existing.text,
        };
      } else {
        if (!action.text.trim()) {
          return state;
        }
        list.push({
          id: action.itemId,
          kind: "message",
          role: "assistant",
          text: action.text,
        });
      }
      const updatedItems = prepareThreadItems(list);
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "upsertItem": {
      let list = state.itemsByThread[action.threadId] ?? [];
      const item = normalizeItem(action.item);
      list = reconcileOptimisticUserMessage(list, item);
      const isUserMessage = item.kind === "message" && item.role === "user";
      const hadUserMessage = isUserMessage
        ? list.some((entry) => entry.kind === "message" && entry.role === "user")
        : false;
      const renameText = isUserMessage ? extractRenameText(item.text) : "";
      if (
        item.kind === "review" &&
        item.state === "started" &&
        !item.id.startsWith("review-start-")
      ) {
        list = dropLatestLocalReviewStart(list);
      }
      if (item.kind === "review" && isDuplicateReviewById(list, item)) {
        return state;
      }
      if (item.kind === "review") {
        const existing = findMatchingReview(list, item);
        if (existing && existing.id !== item.id) {
          return state;
        }
      }
      const nextItem = ensureUniqueReviewId(list, item);
      const updatedItems = prepareThreadItems(upsertItem(list, nextItem));
      let nextThreadsByWorkspace = state.threadsByWorkspace;
      if (isUserMessage) {
        const threads = state.threadsByWorkspace[action.workspaceId] ?? [];
        const textValue = renameText;
        const updatedThreads = threads.map((thread) => {
          if (thread.id !== action.threadId) {
            return thread;
          }
          const looksAutoGenerated = looksAutoGeneratedThreadName(thread.name);
          const shouldRename =
            !hadUserMessage && textValue.length > 0 && looksAutoGenerated && !action.hasCustomName;
          const nextName =
            shouldRename && textValue.length > 38
              ? `${textValue.slice(0, 38)}…`
              : shouldRename
                ? textValue
                : thread.name;
          return { ...thread, name: nextName };
        });
        const bumpedThreads =
          prefersUpdatedSort(state.threadSortKeyByWorkspace, action.workspaceId) &&
          updatedThreads.length
            ? [
                ...updatedThreads.filter((thread) => thread.id === action.threadId),
                ...updatedThreads.filter((thread) => thread.id !== action.threadId),
              ]
            : updatedThreads;
        nextThreadsByWorkspace = {
          ...state.threadsByWorkspace,
          [action.workspaceId]: bumpedThreads,
        };
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "setThreadItems":
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(action.items),
        },
      };
    case "setLastAgentMessage":
      if (state.lastAgentMessageByThread[action.threadId]?.timestamp >= action.timestamp) {
        return state;
      }
      return {
        ...state,
        lastAgentMessageByThread: {
          ...state.lastAgentMessageByThread,
          [action.threadId]: { text: action.text, timestamp: action.timestamp },
        },
      };
    case "appendReasoningSummary": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        summary: mergeStreamingText("summary" in base ? base.summary : "", action.delta),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendReasoningSummaryBoundary": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        summary: addSummaryBoundary("summary" in base ? base.summary : ""),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendReasoningContent": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        content: mergeStreamingText("content" in base ? base.content : "", action.delta),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendPlanDelta": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "tool"
          ? list[index]
          : {
              id: action.itemId,
              kind: "tool",
              toolType: "plan",
              title: "Plan",
              detail: "",
              status: "inProgress",
              output: "",
            };
      const existingOutput = base.kind === "tool" ? (base.output ?? "") : "";
      const updated: ConversationItem = {
        ...(base as ConversationItem),
        kind: "tool",
        toolType: "plan",
        title: "Plan",
        detail: "Generating plan...",
        status: "inProgress",
        output: mergeStreamingText(existingOutput, action.delta),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "appendToolOutput": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      if (index < 0 || list[index].kind !== "tool") {
        return state;
      }
      const existing = list[index];
      const updated: ConversationItem = {
        ...existing,
        output: mergeStreamingText(existing.output ?? "", action.delta),
      } as ConversationItem;
      const next = [...list];
      next[index] = updated;
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next),
        },
      };
    }
    case "completePendingTurnItems": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const completedItems = completePendingTurnItems(list);
      if (completedItems === list) {
        return state;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: completedItems,
        },
      };
    }
    case "addApproval": {
      const exists = state.approvals.some(
        (item) =>
          item.request_id === action.approval.request_id &&
          item.workspace_id === action.approval.workspace_id
      );
      if (exists) {
        return state;
      }
      return { ...state, approvals: [...state.approvals, action.approval] };
    }
    case "removeApproval":
      return {
        ...state,
        approvals: state.approvals.filter(
          (item) => item.request_id !== action.requestId || item.workspace_id !== action.workspaceId
        ),
      };
    case "addUserInputRequest": {
      const exists = state.userInputRequests.some(
        (item) =>
          item.request_id === action.request.request_id &&
          item.workspace_id === action.request.workspace_id
      );
      if (exists) {
        return state;
      }
      return {
        ...state,
        userInputRequests: [...state.userInputRequests, action.request],
      };
    }
    case "removeUserInputRequest":
      return {
        ...state,
        userInputRequests: state.userInputRequests.filter(
          (item) => item.request_id !== action.requestId || item.workspace_id !== action.workspaceId
        ),
      };
    case "addToolCallRequest": {
      const exists = state.toolCallRequests.some(
        (item) =>
          item.request_id === action.request.request_id &&
          item.workspace_id === action.request.workspace_id
      );
      if (exists) {
        return state;
      }
      return {
        ...state,
        toolCallRequests: [...state.toolCallRequests, action.request],
      };
    }
    case "removeToolCallRequest":
      return {
        ...state,
        toolCallRequests: state.toolCallRequests.filter(
          (item) => item.request_id !== action.requestId || item.workspace_id !== action.workspaceId
        ),
      };
    case "setThreads": {
      const hidden = state.hiddenThreadIdsByWorkspace[action.workspaceId] ?? {};
      const visibleThreads = action.threads.filter((thread) => !hidden[thread.id]);
      const existingThreads = state.threadsByWorkspace[action.workspaceId] ?? [];
      const existingById = new Map(existingThreads.map((thread) => [thread.id, thread] as const));
      const reconciled = [...visibleThreads];
      const includedIds = new Set(reconciled.map((thread) => thread.id));
      const activeThreadId = state.activeThreadIdByWorkspace[action.workspaceId];
      const freshenAnchorSummary = (summary: ThreadSummary) => {
        const lastMessageTimestamp = state.lastAgentMessageByThread[summary.id]?.timestamp ?? 0;
        const processingStartedAt = state.threadStatusById[summary.id]?.processingStartedAt ?? 0;
        const nextUpdatedAt = Math.max(
          summary.updatedAt ?? 0,
          lastMessageTimestamp,
          processingStartedAt
        );
        if (nextUpdatedAt <= (summary.updatedAt ?? 0)) {
          return summary;
        }
        return {
          ...summary,
          updatedAt: nextUpdatedAt,
        };
      };
      const appendExistingAnchor = (threadId: string | null | undefined) => {
        if (!threadId || hidden[threadId] || includedIds.has(threadId)) {
          return;
        }
        const summary = existingById.get(threadId);
        if (!summary) {
          return;
        }
        reconciled.push(freshenAnchorSummary(summary));
        includedIds.add(threadId);
      };

      if (activeThreadId && (state.itemsByThread[activeThreadId]?.length ?? 0) > 0) {
        appendExistingAnchor(activeThreadId);
      }
      existingThreads.forEach((thread) => {
        const hasLocalHistory = (state.itemsByThread[thread.id]?.length ?? 0) > 0;
        if (hasLocalHistory || state.threadStatusById[thread.id]?.isProcessing) {
          appendExistingAnchor(thread.id);
        }
      });

      const seedThreadIds = [...includedIds];
      seedThreadIds.forEach((threadId) => {
        const visited = new Set<string>([threadId]);
        let parentId = state.threadParentById[threadId];
        while (parentId && !visited.has(parentId)) {
          visited.add(parentId);
          appendExistingAnchor(parentId);
          parentId = state.threadParentById[parentId];
        }
      });
      const nextActiveThreadId =
        activeThreadId && !includedIds.has(activeThreadId)
          ? (reconciled[0]?.id ?? null)
          : activeThreadId;

      return {
        ...state,
        activeThreadIdByWorkspace:
          nextActiveThreadId === activeThreadId
            ? state.activeThreadIdByWorkspace
            : {
                ...state.activeThreadIdByWorkspace,
                [action.workspaceId]: nextActiveThreadId,
              },
        threadsByWorkspace: {
          ...state.threadsByWorkspace,
          [action.workspaceId]: reconciled,
        },
        threadSortKeyByWorkspace: {
          ...state.threadSortKeyByWorkspace,
          [action.workspaceId]: action.sortKey,
        },
      };
    }
    case "setThreadListLoading":
      return {
        ...state,
        threadListLoadingByWorkspace: {
          ...state.threadListLoadingByWorkspace,
          [action.workspaceId]: action.isLoading,
        },
      };
    case "setThreadResumeLoading":
      return {
        ...state,
        threadResumeLoadingById: {
          ...state.threadResumeLoadingById,
          [action.threadId]: action.isLoading,
        },
      };
    case "setThreadListPaging":
      return {
        ...state,
        threadListPagingByWorkspace: {
          ...state.threadListPagingByWorkspace,
          [action.workspaceId]: action.isLoading,
        },
      };
    case "setThreadListCursor":
      return {
        ...state,
        threadListCursorByWorkspace: {
          ...state.threadListCursorByWorkspace,
          [action.workspaceId]: action.cursor,
        },
      };
    case "setThreadTokenUsage":
      return {
        ...state,
        tokenUsageByThread: {
          ...state.tokenUsageByThread,
          [action.threadId]: action.tokenUsage,
        },
      };
    case "setRateLimits":
      return {
        ...state,
        rateLimitsByWorkspace: {
          ...state.rateLimitsByWorkspace,
          [action.workspaceId]: action.rateLimits,
        },
      };
    case "setAccountInfo":
      return {
        ...state,
        accountByWorkspace: {
          ...state.accountByWorkspace,
          [action.workspaceId]: action.account,
        },
      };
    case "setThreadTurnDiff":
      return {
        ...state,
        turnDiffByThread: {
          ...state.turnDiffByThread,
          [action.threadId]: action.diff,
        },
      };
    case "setThreadPlan":
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: action.plan,
        },
      };
    case "clearThreadPlan":
      return {
        ...state,
        planByThread: {
          ...state.planByThread,
          [action.threadId]: null,
        },
      };
    default:
      return state;
  }
}
