export const semanticThemeVars = {
  borderWidth: {
    default: "1px",
  },
  color: {
    bg: {
      app: "var(--color-background)",
      canvas: "var(--color-canvas, var(--color-background))",
      card: "var(--color-card)",
      composer: "var(--surface-composer, var(--color-surface-1))",
      elevated: "var(--color-surface-elevated)",
      hover: "var(--color-surface-hover)",
      input: "var(--color-input)",
      inset: "var(--color-surface-1)",
      message: "var(--surface-messages, var(--color-surface-0))",
      overlay: "var(--color-overlay)",
      panel: "var(--surface-right-panel, var(--color-surface-2))",
      pressed: "color-mix(in srgb, var(--color-foreground) 10%, var(--color-surface-1))",
      selected: "color-mix(in srgb, var(--color-primary) 12%, var(--color-surface-1))",
      sidebar: "var(--surface-sidebar, var(--color-sidebar, var(--color-surface-1)))",
      topbar: "var(--surface-topbar, var(--color-surface-1))",
    },
    border: {
      accent: "var(--color-primary)",
      default: "var(--color-border)",
      focus: "var(--color-ring)",
      strong: "var(--color-border-strong, color-mix(in srgb, var(--color-border) 82%, black))",
      subtle:
        "var(--color-border-subtle, color-mix(in srgb, var(--color-border) 60%, transparent))",
    },
    control: {
      default: "var(--color-secondary)",
      hover: "var(--color-accent)",
      pressed: "color-mix(in srgb, var(--color-accent-foreground) 8%, var(--color-accent))",
      selected: "color-mix(in srgb, var(--color-primary) 14%, var(--color-secondary))",
    },
    diff: {
      deleteBg: "color-mix(in srgb, var(--color-error) 10%, var(--color-surface-1))",
      deleteBorder: "color-mix(in srgb, var(--color-error) 28%, var(--color-border))",
      gutter: "color-mix(in srgb, var(--color-foreground) 12%, transparent)",
      inlineHighlight: "color-mix(in srgb, var(--color-warning) 18%, transparent)",
      insertBg: "color-mix(in srgb, var(--color-success) 10%, var(--color-surface-1))",
      insertBorder: "color-mix(in srgb, var(--color-success) 28%, var(--color-border))",
      modifiedBg: "color-mix(in srgb, var(--color-info) 10%, var(--color-surface-1))",
      modifiedBorder: "color-mix(in srgb, var(--color-info) 28%, var(--color-border))",
    },
    icon: {
      secondary: "var(--color-fg-secondary)",
    },
    overlay: {
      scrim: "var(--color-overlay)",
    },
    state: {
      cancelled: "color-mix(in srgb, var(--color-fg-secondary) 80%, transparent)",
      danger: "var(--color-error)",
      info: "var(--color-info)",
      offline: "color-mix(in srgb, var(--color-fg-secondary) 72%, transparent)",
      queued: "var(--color-accent-amber)",
      running: "var(--color-primary)",
      streaming: "var(--color-accent-cyan)",
      success: "var(--color-success)",
      thinking: "var(--color-accent-indigo)",
      warning: "var(--color-warning)",
    },
    text: {
      accent: "var(--color-primary)",
      disabled: "color-mix(in srgb, var(--color-fg-secondary) 72%, transparent)",
      inverse: "var(--color-fg-inverted)",
      muted: "var(--color-fg-tertiary)",
      primary: "var(--color-fg-primary)",
      secondary: "var(--color-fg-secondary)",
      tertiary: "var(--color-fg-tertiary)",
    },
  },
  layer: {
    dropdown: "160",
    modal: "220",
    popover: "180",
    toast: "260",
  },
  motion: {
    blur: {
      overlay: "var(--glass-blur-lg)",
    },
    duration: {
      base: "var(--duration-normal)",
      fast: "var(--duration-fast)",
      instant: "0ms",
      slow: "var(--duration-slow)",
    },
    easing: {
      enter: "var(--ease-smooth)",
      exit: "var(--ease-smooth)",
      standard: "var(--ease-smooth)",
    },
    focus: {
      offset: "2px",
      width: "2px",
    },
  },
  radius: {
    lg: "var(--radius-lg)",
    md: "var(--radius-md)",
    pill: "999px",
    sm: "var(--radius-sm)",
    x2: "var(--radius-2xl)",
    xl: "var(--radius-xl)",
    xs: "var(--radius-sm)",
  },
  shadow: {
    lg: "var(--shadow-lg)",
    md: "var(--shadow-md)",
    overlay: "var(--shadow-xl)",
    sm: "var(--shadow-sm)",
    xs: "var(--shadow-xs)",
  },
  size: {
    control: {
      lg: "44px",
      md: "36px",
      sm: "28px",
      xs: "20px",
    },
    layout: {
      composerMaxWidth: "var(--shell-composer-max-width, 46rem)",
      composerMinHeight: "var(--shell-composer-textarea-min-height, 2.5rem)",
      contentMaxWidth: "72rem",
      inspector: "var(--right-panel-width, 22rem)",
      sidebar: "var(--sidebar-width, 272px)",
      sidebarCompact: "72px",
      sidebarRail: "56px",
    },
  },
  space: {
    lg: "var(--spacing-4)",
    md: "var(--spacing-3)",
    px: "var(--spacing-px)",
    sm: "var(--spacing-2)",
    x2: "var(--spacing-6)",
    x3: "var(--spacing-8)",
    x4: "var(--spacing-10)",
    x5: "var(--spacing-12)",
    x6: "var(--spacing-16)",
    xl: "var(--spacing-5)",
    xs: "var(--spacing-1)",
    xxs: "var(--spacing-1)",
  },
  typography: {
    font: {
      mono: "var(--font-mono)",
      ui: "var(--font-sans)",
    },
    lineHeight: {
      md: "var(--line-height-content)",
      sm: "var(--line-height-label)",
      tight: "var(--line-height-title-lg)",
    },
    role: {
      body: "var(--font-size-content)",
      caption: "var(--font-size-chrome)",
      heading: "var(--font-size-title-lg)",
      label: "var(--font-size-label)",
    },
    size: {
      lg: "var(--font-size-label)",
      md: "var(--font-size-chrome)",
      sm: "var(--font-size-meta)",
      x2: "var(--font-size-title-lg)",
      x3: "var(--font-size-display-sm)",
      x4: "var(--font-size-display)",
      xl: "var(--font-size-content)",
      xs: "var(--font-size-tiny)",
    },
    weight: {
      medium: "500",
      semibold: "600",
    },
  },
} as const;

export const componentThemeVars = {
  avatar: {
    background: semanticThemeVars.color.control.default,
    border: semanticThemeVars.color.border.default,
    foreground: semanticThemeVars.color.text.secondary,
    radius: {
      circle: semanticThemeVars.radius.pill,
      rounded: semanticThemeVars.radius.lg,
    },
    size: {
      lg: "var(--spacing-10)",
      md: "var(--spacing-8)",
      sm: "var(--spacing-6)",
    },
  },
  badge: {
    background: {
      accent: "color-mix(in srgb, var(--color-primary) 8%, var(--color-surface-1))",
      danger: "color-mix(in srgb, var(--color-destructive) 8%, var(--color-surface-1))",
      neutral: semanticThemeVars.color.control.default,
      success: "color-mix(in srgb, var(--color-success) 8%, var(--color-surface-1))",
      warning: "color-mix(in srgb, var(--color-warning) 8%, var(--color-surface-1))",
    },
    border: semanticThemeVars.color.border.subtle,
    fontSize: {
      lg: semanticThemeVars.typography.size.sm,
      md: semanticThemeVars.typography.size.md,
      sm: semanticThemeVars.typography.size.xs,
    },
    foreground: {
      accent: "color-mix(in srgb, var(--color-primary) 72%, var(--color-foreground))",
      danger: "color-mix(in srgb, var(--color-destructive) 74%, var(--color-foreground))",
      neutral: semanticThemeVars.color.text.secondary,
      success: "color-mix(in srgb, var(--color-success) 72%, var(--color-foreground))",
      warning: "color-mix(in srgb, var(--color-warning) 72%, var(--color-foreground))",
    },
    gap: semanticThemeVars.space.xs,
    height: {
      lg: "1.875rem",
      md: "1.375rem",
      sm: "1.125rem",
    },
    paddingInline: {
      lg: semanticThemeVars.space.md,
      md: semanticThemeVars.space.sm,
      sm: semanticThemeVars.space.xs,
    },
    radius: {
      chip: semanticThemeVars.radius.xs,
      pill: semanticThemeVars.radius.pill,
    },
  },
  button: {
    background: {
      danger: semanticThemeVars.color.state.danger,
      ghost: "transparent",
      primary: semanticThemeVars.color.state.running,
      secondary: semanticThemeVars.color.control.default,
    },
    border: {
      secondary: semanticThemeVars.color.border.default,
    },
    fontSize: {
      lg: semanticThemeVars.typography.size.xl,
      md: semanticThemeVars.typography.size.lg,
      sm: semanticThemeVars.typography.size.md,
    },
    foreground: {
      danger: semanticThemeVars.color.text.inverse,
      ghost: semanticThemeVars.color.text.secondary,
      primary: semanticThemeVars.color.text.inverse,
      secondary: semanticThemeVars.color.text.primary,
    },
    gap: {
      lg: semanticThemeVars.space.sm,
      md: semanticThemeVars.space.sm,
      sm: semanticThemeVars.space.xs,
    },
    height: {
      lg: semanticThemeVars.size.control.lg,
      md: semanticThemeVars.size.control.md,
      sm: semanticThemeVars.size.control.sm,
    },
    iconRadius: semanticThemeVars.radius.xs,
    radius: semanticThemeVars.radius.md,
  },
  card: {
    border: semanticThemeVars.color.border.default,
    padding: {
      lg: "22px",
      md: "18px",
      sm: "14px",
    },
    surface: semanticThemeVars.color.bg.card,
    surfaceMuted: semanticThemeVars.color.bg.inset,
  },
  dialog: {
    backdrop: semanticThemeVars.color.bg.overlay,
    border: semanticThemeVars.color.border.default,
    description: semanticThemeVars.color.text.secondary,
    footerGap: semanticThemeVars.space.md,
    footerPaddingTop: semanticThemeVars.space.lg,
    headerGap: semanticThemeVars.space.sm,
    margin: semanticThemeVars.space.lg,
    padding: semanticThemeVars.space.xl,
    radius: semanticThemeVars.radius.xl,
    shadow: semanticThemeVars.shadow.lg,
    surface: semanticThemeVars.color.bg.elevated,
    title: semanticThemeVars.color.text.primary,
  },
  diff: {
    deleteBg: semanticThemeVars.color.diff.deleteBg,
    deleteBorder: semanticThemeVars.color.diff.deleteBorder,
    gutter: semanticThemeVars.color.diff.gutter,
    inlineHighlight: semanticThemeVars.color.diff.inlineHighlight,
    insertBg: semanticThemeVars.color.diff.insertBg,
    insertBorder: semanticThemeVars.color.diff.insertBorder,
    modifiedBg: semanticThemeVars.color.diff.modifiedBg,
    modifiedBorder: semanticThemeVars.color.diff.modifiedBorder,
  },
  execution: {
    neutralBorder: semanticThemeVars.color.border.subtle,
    neutralSurface: semanticThemeVars.color.bg.inset,
    neutralText: semanticThemeVars.color.text.secondary,
    selectedBorderMix:
      "color-mix(in srgb, var(--semantic-execution-accent) 34%, var(--semantic-color-border-default))",
  },
  emptyState: {
    actionsGap: semanticThemeVars.space.sm,
    description: semanticThemeVars.color.text.secondary,
    eyebrow: semanticThemeVars.color.text.secondary,
    gap: semanticThemeVars.space.md,
    iconForeground: semanticThemeVars.color.text.primary,
    iconSize: "var(--spacing-10)",
    iconSurface: semanticThemeVars.color.bg.inset,
    title: semanticThemeVars.color.text.primary,
  },
  field: {
    description: semanticThemeVars.color.text.secondary,
    error: semanticThemeVars.color.state.danger,
    gap: semanticThemeVars.space.sm,
    label: semanticThemeVars.color.text.secondary,
    messageGap: semanticThemeVars.space.xs,
  },
  input: {
    background: semanticThemeVars.color.bg.input,
    border: semanticThemeVars.color.border.default,
    errorRing: "color-mix(in srgb, var(--status-error) 22%, transparent)",
    fontSize: semanticThemeVars.typography.size.xl,
    height: semanticThemeVars.size.control.lg,
    padding: "11px 14px",
    placeholder: semanticThemeVars.color.text.tertiary,
    radius: semanticThemeVars.radius.md,
    text: semanticThemeVars.color.text.primary,
  },
  panel: {
    background: "var(--surface-right-panel)",
    border: "var(--border-panel)",
    codeBg: "var(--surface-panel-code)",
    diffAddBg: "var(--surface-panel-diff-add)",
    diffRemoveBg: "var(--surface-panel-diff-remove)",
    focusRing: "var(--focus-panel-ring)",
    footerBorder: "var(--border-panel-sticky)",
    footerShadow: "var(--shadow-panel-sticky)",
    gap: semanticThemeVars.space.md,
    headerBg: "color-mix(in srgb, var(--surface-panel-header) 96%, var(--surface-right-panel))",
    headerMinHeight: semanticThemeVars.size.control.sm,
    headerText: "var(--text-panel-label)",
    highlight: "var(--surface-panel-highlight)",
    label: "var(--text-panel-label)",
    logBg: "var(--surface-panel-log)",
    muted: "var(--text-panel-muted)",
    resizeHandle: "color-mix(in srgb, var(--border-panel-resize-handle) 82%, transparent)",
    rowHover: "var(--surface-panel-row-hover)",
    rowSelected: "var(--surface-panel-row-selected)",
    sectionBg: "var(--surface-panel-section)",
    sectionDivider: "var(--border-panel-divider)",
    subtitle: "var(--text-panel-subtitle)",
    surface: semanticThemeVars.color.bg.panel,
    title: "var(--text-panel-title)",
    value: "var(--text-panel-value)",
  },
  popover: {
    background: semanticThemeVars.color.bg.elevated,
    border: semanticThemeVars.color.border.default,
    enterOffset: "translateY(4px) scale(0.98)",
    enterTransition:
      "opacity var(--duration-normal) var(--ease-smooth), transform var(--duration-normal) var(--ease-smooth)",
    itemHitArea: "34px",
    itemText: semanticThemeVars.color.text.secondary,
    itemTextActive: semanticThemeVars.color.text.primary,
    radius: semanticThemeVars.radius.xl,
    shadow: semanticThemeVars.shadow.lg,
  },
  checkbox: {
    accent: semanticThemeVars.color.border.focus,
    description: semanticThemeVars.color.text.secondary,
    error: semanticThemeVars.color.state.danger,
    focusRing: semanticThemeVars.color.border.focus,
    gap: "10px",
    label: semanticThemeVars.color.text.primary,
    size: "16px",
    topOffset: "2px",
  },
  radioGroup: {
    border: semanticThemeVars.color.border.default,
    borderChecked: semanticThemeVars.color.state.running,
    borderInvalid: semanticThemeVars.color.state.danger,
    cardGap: semanticThemeVars.space.md,
    cardRadius: semanticThemeVars.radius.xl,
    controlBackground: semanticThemeVars.color.control.default,
    description: semanticThemeVars.color.text.secondary,
    dot: semanticThemeVars.color.state.running,
    gap: semanticThemeVars.space.sm,
    indicatorForeground: semanticThemeVars.color.text.inverse,
    label: semanticThemeVars.color.text.primary,
    leadingBackground: semanticThemeVars.color.bg.inset,
    leadingForeground: semanticThemeVars.color.text.secondary,
    optionGap: "10px",
    optionSize: semanticThemeVars.size.control.xs,
  },
  rows: {
    description: semanticThemeVars.color.text.secondary,
    inlineActionGap: "10px",
    inlineActionPadding: "7px 9px",
    inlineActionRadius: semanticThemeVars.radius.sm,
    inlineActionSurface: semanticThemeVars.color.bg.inset,
    inlineActionSurfaceHover: semanticThemeVars.color.control.hover,
    label: semanticThemeVars.color.text.secondary,
    listGap: "4px",
    rowBorder: semanticThemeVars.color.border.subtle,
    rowGap: "8px",
    rowPadding: "5px 0",
    value: semanticThemeVars.color.text.primary,
  },
  select: {
    caretSize: "12px",
    compactCaretSize: "10px",
    compactPaddingX: "7px",
    compactRadius: semanticThemeVars.radius.sm,
    compactTriggerGap: "5px",
    compactTriggerHeight: "26px",
    menuMaxHeight: "280px",
    menuPadding: semanticThemeVars.space.xs,
    menuRadius: semanticThemeVars.radius.lg,
    optionGap: semanticThemeVars.space.sm,
    optionMinHeight: "32px",
    optionRadius: semanticThemeVars.radius.sm,
    paddingX: semanticThemeVars.space.sm,
    radius: semanticThemeVars.radius.md,
    triggerGap: semanticThemeVars.space.xs,
    triggerHeight: "30px",
  },
  sectionHeader: {
    gap: "10px",
    meta: semanticThemeVars.color.text.tertiary,
    title: semanticThemeVars.color.text.tertiary,
  },
  surface: {
    border: semanticThemeVars.color.border.default,
    padding: {
      lg: semanticThemeVars.space.xl,
      md: semanticThemeVars.space.lg,
      sm: "14px",
    },
    radius: semanticThemeVars.radius.xl,
    shadow: semanticThemeVars.shadow.xs,
    surfaceDefault: semanticThemeVars.color.bg.card,
    surfaceElevated: semanticThemeVars.color.bg.elevated,
    surfaceSubtle: semanticThemeVars.color.bg.inset,
  },
  switch: {
    border: semanticThemeVars.color.border.default,
    borderChecked: semanticThemeVars.color.state.running,
    borderInvalid: semanticThemeVars.color.state.danger,
    gap: semanticThemeVars.space.md,
    label: semanticThemeVars.color.text.primary,
    thumb: semanticThemeVars.color.bg.card,
    thumbChecked: semanticThemeVars.color.text.inverse,
    thumbSize: semanticThemeVars.size.control.xs,
    thumbShadow: "rgb(0 0 0 / 0.24)",
    track: semanticThemeVars.color.bg.inset,
    trackChecked: semanticThemeVars.color.state.running,
    trackHeight: semanticThemeVars.size.control.xs,
    trackWidth: "var(--spacing-9)",
  },
  tabs: {
    listBorder: semanticThemeVars.color.border.subtle,
    listSurface: semanticThemeVars.color.control.default,
    triggerMinHeight: "34px",
    triggerSelectedBorder: semanticThemeVars.color.border.subtle,
    triggerSelectedShadow: "0 6px 16px color-mix(in srgb, var(--color-foreground) 8%, transparent)",
    triggerSelectedSurface: semanticThemeVars.color.bg.elevated,
    triggerText: semanticThemeVars.color.text.tertiary,
    triggerTextActive: semanticThemeVars.color.text.primary,
    triggerTextHover: semanticThemeVars.color.text.primary,
    triggerSurfaceHover: semanticThemeVars.color.control.hover,
  },
  text: {
    tone: {
      accent: semanticThemeVars.color.state.running,
      danger: semanticThemeVars.color.state.danger,
      faint: "color-mix(in srgb, var(--color-foreground) 52%, transparent)",
      muted: semanticThemeVars.color.text.secondary,
      strong: semanticThemeVars.color.text.primary,
      success: semanticThemeVars.color.state.success,
      warning: semanticThemeVars.color.state.warning,
    },
  },
  toast: {
    background: semanticThemeVars.color.bg.overlay,
    body: semanticThemeVars.color.text.primary,
    border: semanticThemeVars.color.border.default,
    enterOffsetY: "-4px",
    radius: semanticThemeVars.radius.xl,
    shadow: semanticThemeVars.shadow.lg,
    title: semanticThemeVars.color.text.secondary,
  },
  tooltip: {
    arrowSize: semanticThemeVars.space.sm,
    background: semanticThemeVars.color.bg.elevated,
    border: semanticThemeVars.color.border.default,
    foreground: semanticThemeVars.color.text.primary,
    offset: semanticThemeVars.space.md,
    padding: `${semanticThemeVars.space.xs} ${semanticThemeVars.space.sm}`,
    radius: semanticThemeVars.radius.md,
    shadow: semanticThemeVars.shadow.sm,
  },
  textarea: {
    background: semanticThemeVars.color.bg.input,
    border: semanticThemeVars.color.border.default,
    error: semanticThemeVars.color.state.danger,
    focusRing: semanticThemeVars.color.border.focus,
    placeholder: semanticThemeVars.color.text.tertiary,
    radius: semanticThemeVars.radius.lg,
    size: {
      lg: {
        fontSize: semanticThemeVars.typography.size.xl,
        minHeight: `calc(${semanticThemeVars.size.control.lg} * 2)`,
        paddingBlock: semanticThemeVars.space.md,
        paddingInline: semanticThemeVars.space.lg,
      },
      md: {
        fontSize: semanticThemeVars.typography.size.lg,
        minHeight: `calc(${semanticThemeVars.size.control.md} * 2)`,
        paddingBlock: semanticThemeVars.space.sm,
        paddingInline: "14px",
      },
      sm: {
        fontSize: semanticThemeVars.typography.size.md,
        minHeight: `calc(${semanticThemeVars.size.control.sm} * 2)`,
        paddingBlock: "10px",
        paddingInline: semanticThemeVars.space.md,
      },
    },
    text: semanticThemeVars.color.text.primary,
  },
} as const;

export const executionThemeVars = {
  borderWidth: semanticThemeVars.borderWidth,
  color: {
    bg: {
      card: semanticThemeVars.color.bg.card,
      inset: semanticThemeVars.color.bg.inset,
      panel: semanticThemeVars.color.bg.panel,
    },
    border: {
      default: semanticThemeVars.color.border.default,
      focus: semanticThemeVars.color.border.focus,
      subtle: semanticThemeVars.color.border.subtle,
    },
    state: semanticThemeVars.color.state,
    text: {
      inverse: semanticThemeVars.color.text.inverse,
      primary: semanticThemeVars.color.text.primary,
      secondary: semanticThemeVars.color.text.secondary,
    },
  },
  motion: {
    duration: {
      fast: semanticThemeVars.motion.duration.fast,
    },
    easing: {
      standard: semanticThemeVars.motion.easing.standard,
    },
    focus: {
      width: "var(--ds-focus-ring-width, 2px)",
    },
  },
  radius: {
    lg: semanticThemeVars.radius.lg,
    pill: semanticThemeVars.radius.pill,
    xl: semanticThemeVars.radius.xl,
  },
  size: {
    control: {
      sm: semanticThemeVars.size.control.sm,
      xs: semanticThemeVars.size.control.xs,
    },
    layout: semanticThemeVars.size.layout,
  },
  space: {
    md: semanticThemeVars.space.lg,
    sm: semanticThemeVars.space.md,
    xs: semanticThemeVars.space.sm,
    xxs: semanticThemeVars.space.xs,
  },
  typography: {
    font: {
      mono: semanticThemeVars.typography.font.mono,
    },
    lineHeight: {
      md: semanticThemeVars.typography.lineHeight.md,
      sm: semanticThemeVars.typography.lineHeight.sm,
    },
    role: semanticThemeVars.typography.role,
    weight: semanticThemeVars.typography.weight,
  },
} as const;
