name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node-pnpm
        with:
          registry-url: https://registry.npmjs.org
          install-command: pnpm install --offline --frozen-lockfile

      - uses: ./.github/actions/setup-rust-ci
        with:
          cargo-cache-key: ${{ runner.os }}-release

      - uses: ./.github/actions/install-linux-desktop-deps
        if: ${{ runner.os == 'Linux' }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
